- - report_identifier@MetaData
  - RPID
  - 1
  - &id002 [nlocs, nstring]
  - [-1, 10]
- - sdmedit/quips_quality_mark_for_pressure@MetaData
  - QMPR
  - 2
  - &id001 [nlocs]
  - [-1]
- - sdmedit/quips_quality_mark_for_temperature@MetaData
  - QMAT
  - 2
  - *id001
  - [-1]
- - sdmedit/quips_quality_mark_for_moisture@MetaData
  - QMDD
  - 2
  - *id001
  - [-1]
- - vertical_significance_sfc_observation@ObsValue
  - VSSO
  - 2
  - *id001
  - [-1]
- - sdmedit/quips_quality_mark_for_sea_surface_temperature@MetaData
  - QMST
  - 2
  - *id001
  - [-1]
- - sdmedit/quips_quality_mark_for_wind@MetaData
  - QMWN
  - 2
  - *id001
  - [-1]
- - corrected_report_indicator@MetaData
  - CORN
  - 2
  - *id001
  - [-1]
- - restrictions_on_redistribution@MetaData
  - RSRD
  - 2
  - *id001
  - [-1]
- - expiration_of_restrictions_on_redistribution@MetaData
  - EXPRSRD
  - 3
  - *id001
  - [-1]
- - height_of_station_ground_above_msl@MetaData
  - HSMSL
  - 3
  - *id001
  - [-1]
- - height_of_barometer_above_mean_sea_level@MetaData
  - HBMSL
  - 3
  - *id001
  - [-1]
- - pressure@MetaData
  - PRES
  - 2
  - *id001
  - [-1]
- - pressure_reduced_to_msl@MetaData
  - PMSL
  - 2
  - *id001
  - [-1]
- - 3_hour_pressure_change@MetaData
  - 3HPC
  - 2
  - *id001
  - [-1]
- - characteristic_of_pressure_tendency@MetaData
  - CHPT
  - 2
  - *id001
  - [-1]
- - height_of_sensor_above_water_surface@MetaData
  - HSAWS
  - 3
  - *id001
  - [-1]
- - height_of_sensor_above_local_ground_or_deck_of_marine@MetaData
  - HSALG
  - 3
  - *id001
  - [-1]
- - ice_deposit_thickness@ObsValue
  - IDTH
  - 3
  - *id001
  - [-1]
- - rate_of_ice_accretion@ObsValue
  - ROIA
  - 2
  - *id001
  - [-1]
- - cause_of_ice_accretion@MetaData
  - COIA
  - 2
  - *id001
  - [-1]
- - sea_ice_concentration@ObsValue
  - SICE
  - 2
  - *id001
  - [-1]
- - amount_and_type_of_ice@ObsValue
  - AICE
  - 2
  - *id001
  - [-1]
- - ice_situation@ObsValue
  - ICESI
  - 2
  - *id001
  - [-1]
- - ice_development@ObsValue
  - ICEDV
  - 2
  - *id001
  - [-1]
- - bearing_of_ice_edge@MetaData
  - BOIE
  - 3
  - *id001
  - [-1]
- - channel_sequence_number@MetaData
  - SEQNUM
  - 1
  - *id002
  - [-1, 10]
- - bulletin_being_monitored_ttaaii@MetaData
  - BUHD
  - 1
  - *id002
  - [-1, 10]
- - bulletin_being_monitored_cccc@MetaData
  - BORG
  - 1
  - *id002
  - [-1, 10]
- - bulletin_being_monitored_yygggg@MetaData
  - BULTIM
  - 1
  - *id002
  - [-1, 10]
- - bulletin_being_monitored_bbb@MetaData
  - BBB
  - 1
  - *id002
  - [-1, 10]
- - receipt_time_significance@MetaData
  - RCTS
  - 2
  - *id001
  - [-1]
- - year_time_of_receipt@MetaData
  - RCYR
  - 2
  - *id001
  - [-1]
- - month_time_of_receipt@MetaData
  - RCMO
  - 2
  - *id001
  - [-1]
- - day_time_of_receipt@MetaData
  - RCDY
  - 2
  - *id001
  - [-1]
- - hour_time_of_receipt@MetaData
  - RCHR
  - 3
  - *id001
  - [-1]
- - minute_time_of_receipt@MetaData
  - RCMI
  - 2
  - *id001
  - [-1]
- - ship_call_sign_8_characters@MetaData
  - SHPC8
  - 1
  - *id002
  - [-1, 10]
- - buoy/platform_identifier@MetaData
  - BPID
  - 3
  - *id001
  - [-1]
- - stationary_buoy_platform_id@MetaData
  - SBPI
  - 1
  - *id002
  - [-1, 10]
- - type_of_station@MetaData
  - TOST
  - 2
  - *id001
  - [-1]
- - shef_data_revision_flag@MetaData
  - SHRV
  - 2
  - *id001
  - [-1]
- - shef_data_qualifier_flag@MetaData
  - SHQL
  - 2
  - *id001
  - [-1]
- - temperature/dry_bulb_temperature@ObsValue
  - TMDB
  - 3
  - *id001
  - [-1]
- - method_of_wet_bulb_temperature_measurement@MetaData
  - MWBT
  - 2
  - *id001
  - [-1]
- - wet_bulb_temperature@ObsValue
  - TMWB
  - 3
  - *id001
  - [-1]
- - dew_point_temperature@ObsValue
  - TMDP
  - 3
  - *id001
  - [-1]
- - relative_humidity@ObsValue
  - REHU
  - 3
  - *id001
  - [-1]
- - horizontal_visibility@ObsValue
  - HOVI
  - 3
  - *id001
  - [-1]
- - total_precipitation_past_24_hours@ObsValue
  - TP24
  - 3
  - *id001
  - [-1]
- - cloud_cover_total@ObsValue
  - TOCC
  - 3
  - *id001
  - [-1]
- - cloud_amount@ObsValue
  - CLAM
  - 2
  - *id001
  - [-1]
- - height_of_base_of_cloud@ObsValue
  - HOCB
  - 3
  - *id001
  - [-1]
- - cloud_type@ObsValue
  - CLTP
  - 2
  - *id001
  - [-1]
- - method_of_sea_surface_temperature_measurement@MetaData
  - MSST
  - 2
  - *id001
  - [-1]
- - depth_below_sea/water_surface_cm@MetaData
  - DBSSX
  - 3
  - *id001
  - [-1]
- - sea_temperature@ObsValue
  - SST1
  - 3
  - *id001
  - [-1]
- - direction_of_waves@ObsValue
  - DOWA
  - 3
  - *id001
  - [-1]
- - period_of_waves@ObsValue
  - POWV
  - 3
  - *id001
  - [-1]
- - height_of_waves@ObsValue
  - HOWV
  - 3
  - *id001
  - [-1]
- - present_weather@ObsValue
  - PRWE
  - 2
  - *id001
  - [-1]
- - time_period_or_displacement_2@MetaData
  - TPHR
  - 3
  - *id001
  - [-1]
- - past_weather_1@ObsValue
  - PSW1
  - 2
  - *id001
  - [-1]
- - past_weather_2@ObsValue
  - PSW2
  - 2
  - *id001
  - [-1]
- - maximum_temperature@ObsValue
  - MXTM
  - 3
  - *id001
  - [-1]
- - minimum_temperature@ObsValue
  - MITM
  - 3
  - *id001
  - [-1]
- - type_of_instrumentation_for_wind_measurement@MetaData
  - TIWM
  - 2
  - *id001
  - [-1]
- - time_significance@MetaData
  - TSIG
  - 2
  - *id001
  - [-1]
- - time_period_or_displacement@MetaData
  - TPMI
  - 2
  - *id001
  - [-1]
- - wind_direction@ObsValue
  - WDIR
  - 3
  - *id001
  - [-1]
- - wind_speed@ObsValue
  - WSPD
  - 3
  - *id001
  - [-1]
- - ship_or_mobile_land_station_identifier@MetaData
  - SMID
  - 1
  - *id002
  - [-1, 10]
- - dir._of_motion_of_moving_observing_platform@MetaData
  - DOMO
  - 3
  - *id001
  - [-1]
- - speed_of_motion_of_moving_observing_platform@MetaData
  - SMMO
  - 3
  - *id001
  - [-1]
- - year@MetaData
  - YEAR
  - 2
  - *id001
  - [-1]
- - month@MetaData
  - MNTH
  - 2
  - *id001
  - [-1]
- - day@MetaData
  - DAYS
  - 2
  - *id001
  - [-1]
- - hour@MetaData
  - HOUR
  - 3
  - *id001
  - [-1]
- - minute@MetaData
  - MINU
  - 2
  - *id001
  - [-1]
- - latitude_coarse_accuracy@MetaData
  - CLAT
  - 3
  - *id001
  - [-1]
- - longitude_coarse_accuracy@MetaData
  - CLON
  - 3
  - *id001
  - [-1]
- - forecast_significance@MetaData
  - FCTSIG
  - 2
  - *id001
  - [-1]
- - height_significance@MetaData
  - HGTSIG
  - 2
  - *id001
  - [-1]
- - height@MetaData
  - HEIT
  - 3
  - *id001
  - [-1]
- - discharge_significance@MetaData
  - DCHSIG
  - 2
  - *id001
  - [-1]
- - discharge@MetaData
  - DCHG
  - 3
  - *id001
  - [-1]
- - direction_of_wind_waves@ObsValue
  - DOWW
  - 3
  - *id001
  - [-1]
- - period_of_wind_waves@ObsValue
  - POWW
  - 3
  - *id001
  - [-1]
- - height_of_wind_waves@ObsValue
  - HOWW
  - 3
  - *id001
  - [-1]
