- - report_identifier@MetaData
  - RPID
  - 1
  - &id002 [nlocs, nstring]
  - [-1, 10]
- - wmo_marine_observing_platform_extended_identifier@MetaData
  - WMOP
  - 3
  - &id001 [nlocs]
  - [-1]
- - wmo_region_number@MetaData
  - WMOR
  - 2
  - *id001
  - [-1]
- - wmo_region_subarea@MetaData
  - WMORS4
  - 3
  - *id001
  - [-1]
- - buoy/platform_identifier@MetaData
  - BPID
  - 3
  - *id001
  - [-1]
- - long_station_or_site_name@MetaData
  - LSTN
  - 1
  - *id002
  - [-1, 10]
- - buoy_type@MetaData
  - BUYT
  - 2
  - *id001
  - [-1]
- - time_significance@MetaData
  - TSIG
  - 2
  - *id001
  - [-1]
- - platform_transmitter_id_number@MetaData
  - PTIDC
  - 1
  - *id002
  - [-1, 10]
- - surface_type@MetaData
  - RSST
  - 2
  - *id001
  - [-1]
- - ice_thickness@ObsValue
  - ITHK
  - 3
  - *id001
  - [-1]
- - sdmedit/quips_quality_mark_for_sea_surface_temperature@MetaData
  - QMST
  - 2
  - *id001
  - [-1]
- - precision_of_temperature_observation@MetaData
  - PCAT
  - 3
  - *id001
  - [-1]
- - sdmedit/quips_quality_mark_for_pressure@MetaData
  - QMPR
  - 2
  - *id001
  - [-1]
- - sdmedit/quips_quality_mark_for_temperature@MetaData
  - QMAT
  - 2
  - *id001
  - [-1]
- - height_of_sensor_above_water_surface@MetaData
  - HSAWS
  - 3
  - *id001
  - [-1]
- - temperature/dry_bulb_temperature@ObsValue
  - TMDB
  - 3
  - *id001
  - [-1]
- - dew_point_temperature@ObsValue
  - TMDP
  - 3
  - *id001
  - [-1]
- - relative_humidity@ObsValue
  - REHU
  - 3
  - *id001
  - [-1]
- - data_collection_and/or_location_system@MetaData
  - DCLS
  - 2
  - *id001
  - [-1]
- - dir._of_motion_of_moving_observing_platform@MetaData
  - DOMO
  - 3
  - *id001
  - [-1]
- - platform_drift_speed_high_precision@MetaData
  - PLDS
  - 3
  - *id001
  - [-1]
- - quality_of_buoy_satellite_transmission@MetaData
  - QBST
  - 2
  - *id001
  - [-1]
- - quality_of_buoy_location@MetaData
  - QCIL
  - 2
  - *id001
  - [-1]
- - location_quality_class@MetaData
  - QCLS
  - 2
  - *id001
  - [-1]
- - battery_voltage_large_range@MetaData
  - BVOLH
  - 3
  - *id001
  - [-1]
- - drogue_type@MetaData
  - DROT
  - 2
  - *id001
  - [-1]
- - lagrangian_drifter_drogue_status@MetaData
  - LDDS
  - 2
  - *id001
  - [-1]
- - depth_at_which_drogue_is_attached@MetaData
  - DROD
  - 3
  - *id001
  - [-1]
- - lagrangian_drifter_submergence@MetaData
  - LDRS
  - 3
  - *id001
  - [-1]
- - corrected_report_indicator@MetaData
  - CORN
  - 2
  - *id001
  - [-1]
- - latitude_high_accuracy@MetaData
  - CLATH
  - 3
  - *id001
  - [-1]
- - longitude_high_accuracy@MetaData
  - CLONH
  - 3
  - *id001
  - [-1]
- - year@MetaData
  - YEAR
  - 2
  - *id001
  - [-1]
- - month@MetaData
  - MNTH
  - 2
  - *id001
  - [-1]
- - day@MetaData
  - DAYS
  - 2
  - *id001
  - [-1]
- - hour@MetaData
  - HOUR
  - 3
  - *id001
  - [-1]
- - minute@MetaData
  - MINU
  - 2
  - *id001
  - [-1]
- - indicator_for_digitization@MetaData
  - IDGT
  - 2
  - *id001
  - [-1]
- - method_of_salinity/depth_measurement@MetaData
  - MSDM
  - 2
  - *id001
  - [-1]
- - seasurface_temperature@ObsValue
  - SST0
  - 3
  - *id001
  - [-1]
- - seasurface_salinity@ObsValue
  - SSS0
  - 3
  - *id001
  - [-1]
- - duration_of_wave_record@ObsValue
  - DOWR
  - 3
  - *id001
  - [-1]
- - significant_wave_height@ObsValue
  - SGWH
  - 3
  - *id001
  - [-1]
- - maximum_wave_height@ObsValue
  - MXWH
  - 3
  - *id001
  - [-1]
- - average_wave_period@ObsValue
  - AVWP
  - 3
  - *id001
  - [-1]
- - spectral_peak_wave_period@ObsValue
  - SPWP
  - 3
  - *id001
  - [-1]
- - direction_from_which_dominant_waves_are_coming@ObsValue
  - DDWC
  - 3
  - *id001
  - [-1]
- - directional_spread_of_dominant_wave@ObsValue
  - DSDW
  - 3
  - *id001
  - [-1]
- - pressure@MetaData
  - PRES
  - 2
  - *id001
  - [-1]
- - pressure_reduced_to_msl@MetaData
  - PMSL
  - 2
  - *id001
  - [-1]
- - 3_hour_pressure_change@MetaData
  - 3HPC
  - 2
  - *id001
  - [-1]
- - characteristic_of_pressure_tendency@MetaData
  - CHPT
  - 2
  - *id001
  - [-1]
- - shef_data_revision_flag@MetaData
  - SHRV
  - 2
  - *id001
  - [-1]
- - shef_data_qualifier_flag@MetaData
  - SHQL
  - 2
  - *id001
  - [-1]
- - anemometer_type@MetaData
  - ANTP
  - 2
  - *id001
  - [-1]
- - time_period_or_displacement@MetaData
  - TPMI
  - 2
  - *id001
  - [-1]
- - wind_direction@ObsValue
  - WDIR
  - 3
  - *id001
  - [-1]
- - wind_speed@ObsValue
  - WSPD
  - 3
  - *id001
  - [-1]
- - channel_sequence_number@MetaData
  - SEQNUM
  - 1
  - *id002
  - [-1, 10]
- - bulletin_being_monitored_ttaaii@MetaData
  - BUHD
  - 1
  - *id002
  - [-1, 10]
- - bulletin_being_monitored_cccc@MetaData
  - BORG
  - 1
  - *id002
  - [-1, 10]
- - bulletin_being_monitored_yygggg@MetaData
  - BULTIM
  - 1
  - *id002
  - [-1, 10]
- - bulletin_being_monitored_bbb@MetaData
  - BBB
  - 1
  - *id002
  - [-1, 10]
- - receipt_time_significance@MetaData
  - RCTS
  - 2
  - *id001
  - [-1]
- - year_time_of_receipt@MetaData
  - RCYR
  - 2
  - *id001
  - [-1]
- - month_time_of_receipt@MetaData
  - RCMO
  - 2
  - *id001
  - [-1]
- - day_time_of_receipt@MetaData
  - RCDY
  - 2
  - *id001
  - [-1]
- - hour_time_of_receipt@MetaData
  - RCHR
  - 3
  - *id001
  - [-1]
- - minute_time_of_receipt@MetaData
  - RCMI
  - 2
  - *id001
  - [-1]
- - ship_call_sign_8_characters@MetaData
  - SHPC8
  - 1
  - *id002
  - [-1, 10]
- - stationary_buoy_platform_id@MetaData
  - SBPI
  - 1
  - *id002
  - [-1, 10]
- - depth_below_sea_surface@MetaData
  - DBSS
  - 3
  - *id001
  - [-1]
- - sea_temperature@ObsValue
  - SST1
  - 3
  - *id001
  - [-1]
- - salinity@ObsValue
  - SALN
  - 3
  - *id001
  - [-1]
- - forecast_significance@MetaData
  - FCTSIG
  - 2
  - *id001
  - [-1]
- - height_significance@MetaData
  - HGTSIG
  - 2
  - *id001
  - [-1]
- - height@MetaData
  - HEIT
  - 3
  - *id001
  - [-1]
- - discharge_significance@MetaData
  - DCHSIG
  - 2
  - *id001
  - [-1]
- - discharge@MetaData
  - DCHG
  - 3
  - *id001
  - [-1]
- - usgs_discharge_sensor_type@MetaData
  - DDDC
  - 3
  - *id001
  - [-1]
