- - report_identifier@MetaData
  - RPID
  - 1
  - &id002 [nlocs, nstring]
  - [-1, 10]
- - wmo_region_number@MetaData
  - WMOR
  - 2
  - &id001 [nlocs]
  - [-1]
- - wmo_region_subarea@MetaData
  - WMORS4
  - 3
  - *id001
  - [-1]
- - buoy_platform_identifier@MetaData
  - BPID
  - 3
  - *id001
  - [-1]
- - sdmedit_quips_quality_mark_for_pressure@MetaData
  - QMPR
  - 2
  - *id001
  - [-1]
- - sdmedit_quips_quality_mark_for_temperature@MetaData
  - QMAT
  - 2
  - *id001
  - [-1]
- - sdmedit_quips_quality_mark_for_moisture@MetaData
  - QMDD
  - 2
  - *id001
  - [-1]
- - sdmedit_quips_quality_mark_for_wind@MetaData
  - QMWN
  - 2
  - *id001
  - [-1]
- - 3_hour_pressure_change@MetaData
  - 3HPC
  - 2
  - *id001
  - [-1]
- - characteristic_of_pressure_tendency@MetaData
  - CHPT
  - 2
  - *id001
  - [-1]
- - sdmedit_quips_quality_mark_for_sea_surface_temperature@MetaData
  - QMST
  - 2
  - *id001
  - [-1]
- - precision_of_temperature_observation@MetaData
  - PCAT
  - 3
  - *id001
  - [-1]
- - corrected_report_indicator@MetaData
  - CORN
  - 2
  - *id001
  - [-1]
- - wmo_marine_observing_platform_extended_identifier@MetaData
  - WMOP
  - 3
  - *id001
  - [-1]
- - station_or_site_name@MetaData
  - STSN
  - 1
  - *id002
  - [-1, 10]
- - buoy_type@MetaData
  - BUYT
  - 2
  - *id001
  - [-1]
- - pressure@MetaData
  - PRES
  - 2
  - *id001
  - [-1]
- - pressure_reduced_to_msl@MetaData
  - PMSL
  - 2
  - *id001
  - [-1]
- - height_of_sensor_above_water_surface@MetaData
  - HSAWS
  - 3
  - *id001
  - [-1]
- - temperature_dry_bulb_temperature@ObsValue
  - TMDB
  - 3
  - *id001
  - [-1]
- - dew_point_temperature@ObsValue
  - TMDP
  - 3
  - *id001
  - [-1]
- - relative_humidity@ObsValue
  - REHU
  - 3
  - *id001
  - [-1]
- - time_significance@MetaData
  - TSIG
  - 2
  - *id001
  - [-1]
- - time_period_or_displacement@MetaData
  - TPMI
  - 2
  - *id001
  - [-1]
- - wind_direction@ObsValue
  - WDIR
  - 3
  - *id001
  - [-1]
- - wind_speed@ObsValue
  - WSPD
  - 3
  - *id001
  - [-1]
- - maximum_wind_speed_gusts@ObsValue
  - MXGS
  - 3
  - *id001
  - [-1]
- - depth_below_sea_water_surface_cm@MetaData
  - DBSSX
  - 3
  - *id001
  - [-1]
- - seasurface_temperature@ObsValue
  - SST0
  - 3
  - *id001
  - [-1]
- - indicator_for_digitization@MetaData
  - IDGT
  - 2
  - *id001
  - [-1]
- - method_of_salinity_depth_measurement@MetaData
  - MSDM
  - 2
  - *id001
  - [-1]
- - duration_of_wave_record@ObsValue
  - DOWR
  - 3
  - *id001
  - [-1]
- - significant_wave_height@ObsValue
  - SGWH
  - 3
  - *id001
  - [-1]
- - maximum_wave_height@ObsValue
  - MXWH
  - 3
  - *id001
  - [-1]
- - average_wave_period@ObsValue
  - AVWP
  - 3
  - *id001
  - [-1]
- - spectral_peak_wave_period@ObsValue
  - SPWP
  - 3
  - *id001
  - [-1]
- - direction_from_which_dominant_waves_are_coming@ObsValue
  - DDWC
  - 3
  - *id001
  - [-1]
- - directional_spread_of_dominant_wave@ObsValue
  - DSDW
  - 3
  - *id001
  - [-1]
- - maximum_nondirectional_spectral_wave_density@ObsValue
  - MXSWD
  - 3
  - *id001
  - [-1]
- - horizontal_visibility@ObsValue
  - HOVI
  - 3
  - *id001
  - [-1]
- - time_period_or_displacement_2@MetaData
  - TPHR
  - 3
  - *id001
  - [-1]
- - total_precipitation_total_water_equivalent@ObsValue
  - TOPC
  - 3
  - *id001
  - [-1]
- - longwave_radiation,_integrated_over_period_specified@MetaData
  - LWRAD
  - 3
  - *id001
  - [-1]
- - shortwave_radiation,_integrated_over_period_specified@MetaData
  - SWRAD
  - 3
  - *id001
  - [-1]
- - net_radiation,_integrated_over_period_specified@MetaData
  - NRAD
  - 3
  - *id001
  - [-1]
- - global_solar_radiation_high_accuracy,_integrated_over@MetaData
  - GSORDH
  - 3
  - *id001
  - [-1]
- - diffuse_solar_radiation_high_accuracy,_integrated_ove@MetaData
  - DFSORD
  - 3
  - *id001
  - [-1]
- - direct_solar_radiation_high_accuracy,_integrated_over@MetaData
  - DRSORD
  - 3
  - *id001
  - [-1]
- - duration_&_time_of_current_code@MetaData
  - DTCC
  - 2
  - *id001
  - [-1]
- - channel_sequence_number@MetaData
  - SEQNUM
  - 1
  - *id002
  - [-1, 10]
- - bulletin_being_monitored_ttaaii@MetaData
  - BUHD
  - 1
  - *id002
  - [-1, 10]
- - bulletin_being_monitored_cccc@MetaData
  - BORG
  - 1
  - *id002
  - [-1, 10]
- - bulletin_being_monitored_yygggg@MetaData
  - BULTIM
  - 1
  - *id002
  - [-1, 10]
- - bulletin_being_monitored_bbb@MetaData
  - BBB
  - 1
  - *id002
  - [-1, 10]
- - receipt_time_significance@MetaData
  - RCTS
  - 2
  - *id001
  - [-1]
- - year_time_of_receipt@MetaData
  - RCYR
  - 2
  - *id001
  - [-1]
- - month_time_of_receipt@MetaData
  - RCMO
  - 2
  - *id001
  - [-1]
- - day_time_of_receipt@MetaData
  - RCDY
  - 2
  - *id001
  - [-1]
- - hour_time_of_receipt@MetaData
  - RCHR
  - 3
  - *id001
  - [-1]
- - minute_time_of_receipt@MetaData
  - RCMI
  - 2
  - *id001
  - [-1]
- - ship_call_sign_8_characters@MetaData
  - SHPC8
  - 1
  - *id002
  - [-1, 10]
- - stationary_buoy_platform_id@MetaData
  - SBPI
  - 1
  - *id002
  - [-1, 10]
- - year@MetaData
  - YEAR
  - 2
  - *id001
  - [-1]
- - month@MetaData
  - MNTH
  - 2
  - *id001
  - [-1]
- - day@MetaData
  - DAYS
  - 2
  - *id001
  - [-1]
- - hour@MetaData
  - HOUR
  - 3
  - *id001
  - [-1]
- - minute@MetaData
  - MINU
  - 2
  - *id001
  - [-1]
- - latitude@MetaData
  - CLATH
  - 3
  - *id001
  - [-1]
- - longitude@MetaData
  - CLONH
  - 3
  - *id001
  - [-1]
- - shef_data_revision_flag@MetaData
  - SHRV
  - 2
  - *id001
  - [-1]
- - shef_data_qualifier_flag@MetaData
  - SHQL
  - 2
  - *id001
  - [-1]
- - depth_below_sea_surface@MetaData
  - DBSS
  - 3
  - *id001
  - [-1]
- - sea_temperature@ObsValue
  - SST1
  - 3
  - *id001
  - [-1]
- - salinity@ObsValue
  - SALN
  - 3
  - *id001
  - [-1]
- - waveband_central_frequency@MetaData
  - WCFR
  - 3
  - *id001
  - [-1]
- - spectral_wave_density@ObsValue
  - SWDE
  - 3
  - *id001
  - [-1]
- - mean_direction_from_which_waves_are_coming@ObsValue
  - MDWC
  - 3
  - *id001
  - [-1]
- - principal_direction_from_which_waves_are_coming@ObsValue
  - PDWC
  - 3
  - *id001
  - [-1]
- - first_normalized_polar_coordinate_from_fourier_coeffici@MetaData
  - FNPF
  - 3
  - *id001
  - [-1]
- - second_normalized_polar_coordinate_from_fourier_coeffic@MetaData
  - SNPF
  - 3
  - *id001
  - [-1]
- - direction_of_current@ObsValue
  - DROC
  - 3
  - *id001
  - [-1]
- - speed_of_current@ObsValue
  - SPOC
  - 3
  - *id001
  - [-1]
- - forecast_significance@MetaData
  - FCTSIG
  - 2
  - *id001
  - [-1]
- - height_significance@MetaData
  - HGTSIG
  - 2
  - *id001
  - [-1]
- - height@MetaData
  - HEIT
  - 3
  - *id001
  - [-1]
- - discharge_significance@MetaData
  - DCHSIG
  - 2
  - *id001
  - [-1]
- - discharge@MetaData
  - DCHG
  - 3
  - *id001
  - [-1]
