- - report_identifier@MetaData
  - RPID
  - 1
  - &id002 [nlocs, nstring]
  - [-1, 10]
- - corrected_report_indicator@MetaData
  - CORN
  - 2
  - &id001 [nlocs]
  - [-1]
- - type_of_station@MetaData
  - TOST
  - 2
  - *id001
  - [-1]
- - year@MetaData
  - YEAR
  - 2
  - *id001
  - [-1]
- - month@MetaData
  - MNTH
  - 2
  - *id001
  - [-1]
- - day@MetaData
  - DAYS
  - 2
  - *id001
  - [-1]
- - hour@MetaData
  - HOUR
  - 3
  - *id001
  - [-1]
- - minute@MetaData
  - MINU
  - 2
  - *id001
  - [-1]
- - latitude_coarse_accuracy@MetaData
  - CLAT
  - 3
  - *id001
  - [-1]
- - longitude_coarse_accuracy@MetaData
  - CLON
  - 3
  - *id001
  - [-1]
- - height_of_station@MetaData
  - SELV
  - 3
  - *id001
  - [-1]
- - latitude_high_accuracy@MetaData
  - CLATH
  - 3
  - *id001
  - [-1]
- - longitude_high_accuracy@MetaData
  - CLONH
  - 3
  - *id001
  - [-1]
- - channel_sequence_number@MetaData
  - SEQNUM
  - 1
  - *id002
  - [-1, 10]
- - bulletin_being_monitored_ttaaii@MetaData
  - BUHD
  - 1
  - *id002
  - [-1, 10]
- - bulletin_being_monitored_cccc@MetaData
  - BORG
  - 1
  - *id002
  - [-1, 10]
- - bulletin_being_monitored_yygggg@MetaData
  - BULTIM
  - 1
  - *id002
  - [-1, 10]
- - bulletin_being_monitored_bbb@MetaData
  - BBB
  - 1
  - *id002
  - [-1, 10]
- - receipt_time_significance@MetaData
  - RCTS
  - 2
  - *id001
  - [-1]
- - year_time_of_receipt@MetaData
  - RCYR
  - 2
  - *id001
  - [-1]
- - month_time_of_receipt@MetaData
  - RCMO
  - 2
  - *id001
  - [-1]
- - day_time_of_receipt@MetaData
  - RCDY
  - 2
  - *id001
  - [-1]
- - hour_time_of_receipt@MetaData
  - RCHR
  - 3
  - *id001
  - [-1]
- - minute_time_of_receipt@MetaData
  - RCMI
  - 2
  - *id001
  - [-1]
- - type_of_instrumentation_for_wind_measurement@MetaData
  - TIWM
  - 2
  - *id001
  - [-1]
- - sdmedit/quips_quality_mark_for_wind@MetaData
  - QMWN
  - 2
  - *id001
  - [-1]
- - wind_direction@ObsValue
  - WDIR
  - 3
  - *id001
  - [-1]
- - wind_speed@ObsValue
  - WSPD
  - 3
  - *id001
  - [-1]
- - sdmedit/quips_quality_mark_for_temperature@MetaData
  - QMAT
  - 2
  - *id001
  - [-1]
- - temperature/dry_bulb_temperature@ObsValue
  - TMDB
  - 3
  - *id001
  - [-1]
- - sdmedit/quips_quality_mark_for_moisture@MetaData
  - QMDD
  - 2
  - *id001
  - [-1]
- - dew_point_temperature@ObsValue
  - TMDP
  - 3
  - *id001
  - [-1]
- - relative_humidity@ObsValue
  - REHU
  - 3
  - *id001
  - [-1]
- - sdmedit/quips_quality_mark_for_sea_surface_temperature@MetaData
  - QMST
  - 2
  - *id001
  - [-1]
- - sea_temperature@ObsValue
  - SST1
  - 3
  - *id001
  - [-1]
- - sdmedit/quips_quality_mark_for_pressure@MetaData
  - QMPR
  - 2
  - *id001
  - [-1]
- - pressure@MetaData
  - PRES
  - 2
  - *id001
  - [-1]
- - pressure_reduced_to_msl@MetaData
  - PMSL
  - 2
  - *id001
  - [-1]
- - characteristic_of_pressure_tendency@MetaData
  - CHPT
  - 2
  - *id001
  - [-1]
- - 3_hour_pressure_change@MetaData
  - 3HPC
  - 2
  - *id001
  - [-1]
- - period_of_waves@ObsValue
  - POWV
  - 3
  - *id001
  - [-1]
- - sdmedit/quips_quality_mark_for_wave_height@MetaData
  - QMWH
  - 2
  - *id001
  - [-1]
- - height_of_waves@ObsValue
  - HOWV
  - 3
  - *id001
  - [-1]
- - quality_of_buoy_satellite_transmission@MetaData
  - QBST
  - 2
  - *id001
  - [-1]
- - quality_of_buoy_location@MetaData
  - QCIL
  - 2
  - *id001
  - [-1]
- - location_quality_class@MetaData
  - QCLS
  - 2
  - *id001
  - [-1]
- - depths_corr._using_hydrostatic_press._indicator@MetaData
  - QDEP
  - 2
  - *id001
  - [-1]
- - quality_control_indicator_for_temp/salinity_profile@MetaData
  - QCTSP
  - 2
  - *id001
  - [-1]
- - quality_control_indicator_for_current_profile@MetaData
  - QCCUR
  - 2
  - *id001
  - [-1]
- - method_of_salinity/depth_measurement@MetaData
  - MSDM
  - 2
  - *id001
  - [-1]
- - meth_rmv_code_veloc_&_motion_of_platform_from_curr_meas@MetaData
  - MRMV
  - 2
  - *id001
  - [-1]
- - duration_&_time_of_current_code@MetaData
  - DTCC
  - 2
  - *id001
  - [-1]
- - depth_below_sea_surface@MetaData
  - DBSS
  - 3
  - *id001
  - [-1]
- - sea_temperature_at_specified_depth@ObsValue
  - STMP
  - 3
  - *id001
  - [-1]
- - salinity@ObsValue
  - SALN
  - 3
  - *id001
  - [-1]
- - direction_of_current@ObsValue
  - DROC
  - 3
  - *id001
  - [-1]
- - speed_of_current@ObsValue
  - SPOC
  - 3
  - *id001
  - [-1]
- - report_year_of_last_known_position_of_buoy@MetaData
  - PSYR
  - 2
  - *id001
  - [-1]
- - report_month_of_last_known_position_of_buoy@MetaData
  - PSMN
  - 2
  - *id001
  - [-1]
- - report_day_of_last_known_position_of_buoy@MetaData
  - PSDY
  - 2
  - *id001
  - [-1]
- - report_hour_of_last_known_position_of_buoy@MetaData
  - PSHR
  - 3
  - *id001
  - [-1]
- - report_minute_of_last_known_position_of_buoy@MetaData
  - PSMI
  - 2
  - *id001
  - [-1]
- - platform_drift_speed_high_precision@MetaData
  - PLDS
  - 3
  - *id001
  - [-1]
- - dir._of_motion_of_moving_observing_platform@MetaData
  - DOMO
  - 3
  - *id001
  - [-1]
- - latitude_high_accuracy_2@MetaData
  - DLATH
  - 3
  - *id001
  - [-1]
- - longitude_high_accuracy_2@MetaData
  - DLONH
  - 3
  - *id001
  - [-1]
- - drogue_type@MetaData
  - DROT
  - 2
  - *id001
  - [-1]
- - depth_at_which_drogue_is_attached@MetaData
  - DROD
  - 3
  - *id001
  - [-1]
- - hydrostatic_press._at_lower_end_of_cable@MetaData
  - HPLE
  - 2
  - *id001
  - [-1]
- - cable_length_thermistor_string@MetaData
  - CALT
  - 3
  - *id001
  - [-1]
- - buoy_type@MetaData
  - BUYT
  - 2
  - *id001
  - [-1]
- - anemometer_height@MetaData
  - ANHT
  - 3
  - *id001
  - [-1]
- - anemometer_height_when_artificially_corrected@MetaData
  - AHAC
  - 3
  - *id001
  - [-1]
- - anemometer_type@MetaData
  - ANTP
  - 2
  - *id001
  - [-1]
- - lagrangian_drifter_drogue_status@MetaData
  - LDDS
  - 2
  - *id001
  - [-1]
- - lagrangian_drifter_submergence@MetaData
  - LDRS
  - 3
  - *id001
  - [-1]
- - battery_voltage@MetaData
  - BVOL
  - 3
  - *id001
  - [-1]
- - raw_report_string@MetaData
  - RRSTG
  - 1
  - *id002
  - [-1, 10]
- - ship_call_sign_8_characters@MetaData
  - SHPC8
  - 1
  - *id002
  - [-1, 10]
- - buoy/platform_identifier@MetaData
  - BPID
  - 3
  - *id001
  - [-1]
- - stationary_buoy_platform_id@MetaData
  - SBPI
  - 1
  - *id002
  - [-1, 10]
- - shef_data_revision_flag@MetaData
  - SHRV
  - 2
  - *id001
  - [-1]
- - shef_data_qualifier_flag@MetaData
  - SHQL
  - 2
  - *id001
  - [-1]
- - time_significance@MetaData
  - TSIG
  - 2
  - *id001
  - [-1]
- - forecast_significance@MetaData
  - FCTSIG
  - 2
  - *id001
  - [-1]
- - height_significance@MetaData
  - HGTSIG
  - 2
  - *id001
  - [-1]
- - height@MetaData
  - HEIT
  - 3
  - *id001
  - [-1]
- - discharge_significance@MetaData
  - DCHSIG
  - 2
  - *id001
  - [-1]
- - discharge@MetaData
  - DCHG
  - 3
  - *id001
  - [-1]
