- - corrected_report_indicator@MetaData
  - CORN
  - 2
  - &id001 [nlocs]
  - [-1]
- - satellite_identifier@MetaData
  - SAID
  - 2
  - *id001
  - [-1]
- - satellite_instruments@MetaData
  - SIID
  - 2
  - *id001
  - [-1]
- - station_acquisition@MetaData
  - STAQ
  - 1
  - &id002 [nlocs, nstring]
  - [-1, 10]
- - software_identification_and_version_number@MetaData
  - SOFTV
  - 1
  - *id002
  - [-1, 10]
- - satellite_cycle_number@MetaData
  - SACYLN
  - 3
  - *id001
  - [-1]
- - orbit_number@MetaData
  - ORBN
  - 3
  - *id001
  - [-1]
- - numerical_model_identifier@MetaData
  - NUMID
  - 1
  - *id002
  - [-1, 10]
- - year@MetaData
  - YEAR
  - 2
  - *id001
  - [-1]
- - month@MetaData
  - MNTH
  - 2
  - *id001
  - [-1]
- - day@MetaData
  - DAYS
  - 2
  - *id001
  - [-1]
- - hour@MetaData
  - HOUR
  - 3
  - *id001
  - [-1]
- - minute@MetaData
  - MINU
  - 2
  - *id001
  - [-1]
- - second_within_a_minute_microsecond_accuracy@MetaData
  - SECW
  - 3
  - *id001
  - [-1]
- - latitude@MetaData
  - CLATH
  - 3
  - *id001
  - [-1]
- - longitude@MetaData
  - CLONH
  - 3
  - *id001
  - [-1]
- - remotely_sensed_surface_type@MetaData
  - RSST
  - 2
  - *id001
  - [-1]
- - radiometer_sensed_surface_type@MetaData
  - DSST
  - 2
  - *id001
  - [-1]
- - interpolation_flag@MetaData
  - INTF
  - 2
  - *id001
  - [-1]
- - 3d_error_estimate_of_the_navigator_orbit@MetaData
  - EENO
  - 2
  - *id001
  - [-1]
- - band_specific_altimeter_data_quality_flag@MetaData
  - BSADQF
  - 2
  - *id001
  - [-1]
- - band_specific_altimeter_correction_quality_flag@MetaData
  - BSACQF
  - 2
  - *id001
  - [-1]
- - trailing_edge_variation_flag@MetaData
  - TEVF
  - 2
  - *id001
  - [-1]
- - ice_presence_indicator@MetaData
  - IPIN
  - 2
  - *id001
  - [-1]
- - meteorological_map_availability@MetaData
  - MMAC
  - 2
  - *id001
  - [-1]
- - interpolation_flag_for_mean_diurnal_tide@MetaData
  - IFDT
  - 2
  - *id001
  - [-1]
- - satellite_channel_center_frequency@MetaData
  - SCCF
  - 3
  - *id001
  - [-1]
- - specific_band_ocean_range@MetaData
  - SBOCR
  - 3
  - *id001
  - [-1]
- - rms_of_specific_band_ocean_range@MetaData
  - RMSOCR
  - 3
  - *id001
  - [-1]
- - number_of_valid_points_for_specific_band@MetaData
  - NVPSB
  - 3
  - *id001
  - [-1]
- - specific_band_net_instrumental_correction@MetaData
  - SBNIC
  - 3
  - *id001
  - [-1]
- - sea_state_bias_correction_on_specific_band@MetaData
  - SBCSB
  - 3
  - *id001
  - [-1]
- - specific_band_significant_wave_height@ObsValue
  - SBSWH
  - 3
  - *id001
  - [-1]
- - rms_specific_band_significant_wave_height@ObsValue
  - RMSSWH
  - 3
  - *id001
  - [-1]
- - number_of_valid_points_for_specific_band_significant_wa@MetaData
  - NVPSWH
  - 3
  - *id001
  - [-1]
- - specific_band_net_instrument_correction_for_signficant@MetaData
  - NISWH
  - 3
  - *id001
  - [-1]
- - specific_band_corrected_ocean_backscatter_coefficient@MetaData
  - COBC
  - 3
  - *id001
  - [-1]
- - std_specific_band_corrected_ocean_backscatter_coefficie@MetaData
  - SCOBC
  - 3
  - *id001
  - [-1]
- - number_of_valid_points_for_specific_band_backscatter@MetaData
  - NVPBS
  - 3
  - *id001
  - [-1]
- - specific_band_net_instrumental_correction_for_agc@MetaData
  - NIAGC
  - 3
  - *id001
  - [-1]
- - attenuation_correction_on_sigma0@MetaData
  - ACRS
  - 3
  - *id001
  - [-1]
- - specific_band_automatic_gain_control@MetaData
  - SAGC
  - 3
  - *id001
  - [-1]
- - rms_specific_band_automatic_gain_control@MetaData
  - RMSAGC
  - 3
  - *id001
  - [-1]
- - number_of_valid_points_for_specific_band_automatic_gain@MetaData
  - NVPAGC
  - 3
  - *id001
  - [-1]
- - brightness_temperature@ObsValue
  - TMBRST
  - 3
  - *id001
  - [-1]
- - radiometer_water_vapor_content@MetaData
  - RWVC
  - 3
  - *id001
  - [-1]
- - radiometer_liquid_content@MetaData
  - RDLC
  - 3
  - *id001
  - [-1]
- - height_or_altitude@MetaData
  - HMSL
  - 3
  - *id001
  - [-1]
- - wind_speed_from_altimeter@ObsValue
  - WSPA
  - 3
  - *id001
  - [-1]
- - ucomponent_of_the_model_wind_vector@ObsValue
  - UMWV
  - 3
  - *id001
  - [-1]
- - vcomponent_of_the_model_wind_vector@ObsValue
  - VWMV
  - 3
  - *id001
  - [-1]
- - mean_dynamic_topography@ObsValue
  - MDYT
  - 3
  - *id001
  - [-1]
- - altitude_of_cog_above_reference_ellipsoid@MetaData
  - ALRE
  - 3
  - *id001
  - [-1]
- - instantaneous_altitude_rate@MetaData
  - IALR
  - 3
  - *id001
  - [-1]
- - squared_off_nadir_angle_of_the_satellite_from_platform@MetaData
  - ONAP
  - 3
  - *id001
  - [-1]
- - squared_off_nadir_angle_of_the_satellite_from_waveform@MetaData
  - SONAW
  - 3
  - *id001
  - [-1]
- - ionospheric_correction_from_model_on_specific_band@MetaData
  - ICMSB
  - 3
  - *id001
  - [-1]
- - model_dry_tropospheric_correction@MetaData
  - MDTC
  - 3
  - *id001
  - [-1]
- - model_wet_tropospheric_correction@MetaData
  - MWTC
  - 3
  - *id001
  - [-1]
- - radiometer_wet_tropospheric_correction@MetaData
  - RWTC
  - 3
  - *id001
  - [-1]
- - mean_seasurface_height@ObsValue
  - MSSH
  - 3
  - *id001
  - [-1]
- - geoid's_height@MetaData
  - GEODH
  - 3
  - *id001
  - [-1]
- - ocean_depth_land_elevation@ObsValue
  - ODLE
  - 3
  - *id001
  - [-1]
- - solid_earth_tide_height@MetaData
  - SETH
  - 3
  - *id001
  - [-1]
- - total_geocentric_ocean_tide_height_solution_1@MetaData
  - TGOTH1
  - 3
  - *id001
  - [-1]
- - total_geocentric_ocean_tide_height_solution_2@MetaData
  - TGOTH2
  - 3
  - *id001
  - [-1]
- - loading_tide_height_geocentric_ocean_tide_solution_1@MetaData
  - LTHS1
  - 3
  - *id001
  - [-1]
- - loading_tide_height_geocentric_ocean_tide_solution_2@MetaData
  - LTHS2
  - 3
  - *id001
  - [-1]
- - long_period_tide_height@MetaData
  - LPTH
  - 3
  - *id001
  - [-1]
- - nonequilibrium_long_period_tide_height@MetaData
  - NLTH
  - 3
  - *id001
  - [-1]
- - geocentric_pole_tide_height@MetaData
  - GPTH
  - 3
  - *id001
  - [-1]
- - inverted_barometer_correction@MetaData
  - IBCO
  - 3
  - *id001
  - [-1]
- - high_frequency_fluctuations_of_the_sea_surface_topograp@MetaData
  - HFSTC
  - 3
  - *id001
  - [-1]
- - sea_surface_height_anomoly@ObsValue
  - SSHA
  - 3
  - *id001
  - [-1]
- - channel_sequence_number@MetaData
  - SEQNUM
  - 1
  - *id002
  - [-1, 10]
- - bulletin_being_monitored_ttaaii@MetaData
  - BUHD
  - 1
  - *id002
  - [-1, 10]
- - bulletin_being_monitored_cccc@MetaData
  - BORG
  - 1
  - *id002
  - [-1, 10]
- - bulletin_being_monitored_yygggg@MetaData
  - BULTIM
  - 1
  - *id002
  - [-1, 10]
- - bulletin_being_monitored_bbb@MetaData
  - BBB
  - 1
  - *id002
  - [-1, 10]
- - receipt_time_significance@MetaData
  - RCTS
  - 2
  - *id001
  - [-1]
- - year_time_of_receipt@MetaData
  - RCYR
  - 2
  - *id001
  - [-1]
- - month_time_of_receipt@MetaData
  - RCMO
  - 2
  - *id001
  - [-1]
- - day_time_of_receipt@MetaData
  - RCDY
  - 2
  - *id001
  - [-1]
- - hour_time_of_receipt@MetaData
  - RCHR
  - 3
  - *id001
  - [-1]
- - minute_time_of_receipt@MetaData
  - RCMI
  - 2
  - *id001
  - [-1]
