- - corrected_report_indicator@MetaData
  - CORN
  - 2
  - &id001 [nlocs]
  - [-1]
- - satellite_identifier@MetaData
  - SAID
  - 2
  - *id001
  - [-1]
- - satellite_instruments@MetaData
  - SIID
  - 2
  - *id001
  - [-1]
- - siral_instrument_configuration@MetaData
  - SIIC
  - 2
  - *id001
  - [-1]
- - station_acquisition@MetaData
  - STAQ
  - 1
  - &id002 [nlocs, nstring]
  - [-1, 10]
- - processing_centre_id_code@MetaData
  - PCID
  - 1
  - *id002
  - [-1, 10]
- - software_identification_and_version_number@MetaData
  - SOFTV
  - 1
  - *id002
  - [-1, 10]
- - orbit_number@MetaData
  - ORBN
  - 3
  - *id001
  - [-1]
- - satellite_cycle_number@MetaData
  - SACYLN
  - 3
  - *id001
  - [-1]
- - ascending_descending_orbit_qualifier@MetaData
  - STKO
  - 2
  - *id001
  - [-1]
- - radiometer_sensed_surface_type@MetaData
  - DSST
  - 2
  - *id001
  - [-1]
- - year@MetaData
  - YEAR
  - 2
  - *id001
  - [-1]
- - month@MetaData
  - MNTH
  - 2
  - *id001
  - [-1]
- - day@MetaData
  - DAYS
  - 2
  - *id001
  - [-1]
- - hour@MetaData
  - HOUR
  - 3
  - *id001
  - [-1]
- - minute@MetaData
  - MINU
  - 2
  - *id001
  - [-1]
- - second@MetaData
  - SECO
  - 3
  - *id001
  - [-1]
- - latitude@MetaData
  - CLATH
  - 3
  - *id001
  - [-1]
- - longitude@MetaData
  - CLONH
  - 3
  - *id001
  - [-1]
- - altitude_of_cog_above_reference_ellipsoid@MetaData
  - ALRE
  - 3
  - *id001
  - [-1]
- - ku_band_significant_wave_height@ObsValue
  - KBSW
  - 3
  - *id001
  - [-1]
- - square_of_significant_wave_height@ObsValue
  - SWHS
  - 3
  - *id001
  - [-1]
- - std_of_20_hz_swh_squared@MetaData
  - S20SWHS
  - 3
  - *id001
  - [-1]
- - number_of_20_hz_valid_points_for_swh_squared@MetaData
  - N20SWHS
  - 3
  - *id001
  - [-1]
- - ku_band_corrected_ocean_backscatter_coefficient@MetaData
  - KOBC
  - 3
  - *id001
  - [-1]
- - std_ku_band_corrected_ocean_backscatter_coefficient@MetaData
  - SKOBC
  - 3
  - *id001
  - [-1]
- - number_of_20_hz_valid_points_for_ocean_backscatter_coef@MetaData
  - N20NBC
  - 3
  - *id001
  - [-1]
- - corrected_ocog_backscatter_coefficient@MetaData
  - CGBC
  - 3
  - *id001
  - [-1]
- - std_of_20_hz_ocog_backscatter_coefficient@MetaData
  - S20GBC
  - 3
  - *id001
  - [-1]
- - number_of_20_hz_valid_points_for_ocog_backscatter_coeff@MetaData
  - N20GBC
  - 3
  - *id001
  - [-1]
- - off_nadir_angle_of_the_satellite_from_platform_data@MetaData
  - ONAS
  - 3
  - *id001
  - [-1]
- - mean_seasurface_height@ObsValue
  - MSSH
  - 3
  - *id001
  - [-1]
- - geoid's_height@MetaData
  - GEODH
  - 3
  - *id001
  - [-1]
- - ocean_depth_land_elevation@ObsValue
  - ODLE
  - 3
  - *id001
  - [-1]
- - total_geocentric_ocean_tide_height_solution_2@MetaData
  - TGOTH2
  - 3
  - *id001
  - [-1]
- - long_period_tide_height@MetaData
  - LPTH
  - 3
  - *id001
  - [-1]
- - tidal_loading_height@MetaData
  - TILH
  - 3
  - *id001
  - [-1]
- - solid_earth_tide_height@MetaData
  - SETH
  - 3
  - *id001
  - [-1]
- - geocentric_pole_tide_height@MetaData
  - GPTH
  - 3
  - *id001
  - [-1]
- - wind_speed_from_altimeter@ObsValue
  - WSPA
  - 3
  - *id001
  - [-1]
- - ku_band_peakiness@MetaData
  - KUBP
  - 3
  - *id001
  - [-1]
- - ku_band_ocean_retracking_quality@MetaData
  - KORQ
  - 2
  - *id001
  - [-1]
- - ku_band_ocean_range@MetaData
  - KBOR
  - 3
  - *id001
  - [-1]
- - std_of_20_hz_ocean_range@MetaData
  - S20NR
  - 3
  - *id001
  - [-1]
- - number_of_20_hz_valid_points_for_ocean_range@MetaData
  - N20NR
  - 3
  - *id001
  - [-1]
- - ocog_range@MetaData
  - GRAN
  - 3
  - *id001
  - [-1]
- - std_of_20_hz_ocog_range@MetaData
  - S20GR
  - 3
  - *id001
  - [-1]
- - model_dry_tropospheric_correction@MetaData
  - MDTC
  - 3
  - *id001
  - [-1]
- - model_wet_tropospheric_correction@MetaData
  - MWTC
  - 3
  - *id001
  - [-1]
- - inverted_barometer_correction@MetaData
  - IBCO
  - 3
  - *id001
  - [-1]
- - high_frequency_variability_correction@MetaData
  - HFVC
  - 3
  - *id001
  - [-1]
- - ionospheric_correction_from_model_on_ku_band@MetaData
  - ICMK
  - 3
  - *id001
  - [-1]
- - sea_state_bias_correction_on_ku_band@MetaData
  - SBCK
  - 3
  - *id001
  - [-1]
- - l1_processing_flag@MetaData
  - L1PF
  - 2
  - *id001
  - [-1]
- - l1_processing_quality@MetaData
  - L1PQ
  - 3
  - *id001
  - [-1]
- - lrm_mode_per_cent@MetaData
  - LRMP
  - 3
  - *id001
  - [-1]
- - l2_product_status@MetaData
  - L2PS
  - 2
  - *id001
  - [-1]
- - l2_processing_flag@MetaData
  - L2PF
  - 2
  - *id001
  - [-1]
- - scan_level_quality_flags@MetaData
  - ATMSSQ
  - 2
  - *id001
  - [-1]
- - channel_sequence_number@MetaData
  - SEQNUM
  - 1
  - *id002
  - [-1, 10]
- - bulletin_being_monitored_ttaaii@MetaData
  - BUHD
  - 1
  - *id002
  - [-1, 10]
- - bulletin_being_monitored_cccc@MetaData
  - BORG
  - 1
  - *id002
  - [-1, 10]
- - bulletin_being_monitored_yygggg@MetaData
  - BULTIM
  - 1
  - *id002
  - [-1, 10]
- - bulletin_being_monitored_bbb@MetaData
  - BBB
  - 1
  - *id002
  - [-1, 10]
- - receipt_time_significance@MetaData
  - RCTS
  - 2
  - *id001
  - [-1]
- - year_time_of_receipt@MetaData
  - RCYR
  - 2
  - *id001
  - [-1]
- - month_time_of_receipt@MetaData
  - RCMO
  - 2
  - *id001
  - [-1]
- - day_time_of_receipt@MetaData
  - RCDY
  - 2
  - *id001
  - [-1]
- - hour_time_of_receipt@MetaData
  - RCHR
  - 3
  - *id001
  - [-1]
- - minute_time_of_receipt@MetaData
  - RCMI
  - 2
  - *id001
  - [-1]
