- - report_identifier@MetaData
  - RPID
  - 1
  - &id002 [nlocs, nstring]
  - [-1, 20]
- - corrected_report_indicator@MetaData
  - CORN
  - 2
  - &id001 [nlocs]
  - [-1]
- - indicator_for_digitization@MetaData
  - IDGT
  - 2
  - *id001
  - [-1]
- - instrument_type_for_water_temperature_profile@MetaData
  - IWTEMP
  - 2
  - *id001
  - [-1]
- - water_temperature_profile_recorder_types@MetaData
  - WTEMPR
  - 2
  - *id001
  - [-1]
- - method_of_salinity_depth_measurement@MetaData
  - MSDM
  - 2
  - *id001
  - [-1]
- - total_water_depth@ObsValue
  - TOWD
  - 3
  - *id001
  - [-1]
- - meth_of_rmv_velocity_and_motion_of_platform_from_current@MetaData
  - MRMV
  - 2
  - *id001
  - [-1]
- - year@MetaData
  - YEAR
  - 2
  - *id001
  - [-1]
- - month@MetaData
  - MNTH
  - 2
  - *id001
  - [-1]
- - day@MetaData
  - DAYS
  - 2
  - *id001
  - [-1]
- - hour@MetaData
  - HOUR
  - 3
  - *id001
  - [-1]
- - minute@MetaData
  - MINU
  - 2
  - *id001
  - [-1]
- - second@MetaData
  - SECO
  - 3
  - *id001
  - [-1]
- - receipt_time_significance@MetaData
  - RCTS
  - 2
  - *id001
  - [-1]
- - year_time_of_receipt@MetaData
  - RCYR
  - 2
  - *id001
  - [-1]
- - month_time_of_receipt@MetaData
  - RCMO
  - 2
  - *id001
  - [-1]
- - day_time_of_receipt@MetaData
  - RCDY
  - 2
  - *id001
  - [-1]
- - hour_time_of_receipt@MetaData
  - RCHR
  - 3
  - *id001
  - [-1]
- - minute_time_of_receipt@MetaData
  - RCMI
  - 2
  - *id001
  - [-1]
- - height_of_station@MetaData
  - SELV
  - 3
  - *id001
  - [-1]
- - latitude@MetaData
  - CLATH
  - 3
  - *id001
  - [-1]
- - longitude@MetaData
  - CLONH
  - 3
  - *id001
  - [-1]
- - channel_sequence_number@MetaData
  - SEQNUM
  - 1
  - *id002
  - [-1, 20]
- - bulletin_being_monitored_ttaaii@MetaData
  - BUHD
  - 1
  - *id002
  - [-1, 20]
- - bulletin_being_monitored_cccc@MetaData
  - BORG
  - 1
  - *id002
  - [-1, 20]
- - bulletin_being_monitored_yygggg@MetaData
  - BULTIM
  - 1
  - *id002
  - [-1, 20]
- - bulletin_being_monitored_bbb@MetaData
  - BBB
  - 1
  - *id002
  - [-1, 20]
- - type_of_instrumentation_for_wind_measurement@MetaData
  - TIWM
  - 2
  - *id001
  - [-1]
- - quips_quality_mark_for_wind@MetaData
  - QMWN
  - 2
  - *id001
  - [-1]
- - wind_direction@ObsValue
  - WDIR
  - 3
  - *id001
  - [-1]
- - wind_speed@ObsValue
  - WSPD
  - 3
  - *id001
  - [-1]
- - quips_quality_mark_for_temperature@MetaData
  - QMAT
  - 2
  - *id001
  - [-1]
- - temperature_dry_bulb_temperature@ObsValue
  - TMDB
  - 3
  - *id001
  - [-1]
- - duration_and_time_of_current_measurement@MetaData
  - DTCC
  - 2
  - *id001
  - [-1]
- - ship_call_sign_8_characters@MetaData
  - SHPC8
  - 1
  - *id002
  - [-1, 20]
- - buoy_platform_identifier@MetaData
  - BPID
  - 3
  - *id001
  - [-1]
- - stationary_buoy_platform_id@MetaData
  - SBPI
  - 1
  - *id002
  - [-1, 20]
- - maximum_wind_speed_gusts@ObsValue
  - MXGS
  - 3
  - *id001
  - [-1]
