- - report_identifier@MetaData
  - RPID
  - 1
  - &id001 [nlocs, nstring]
  - [-1, 20]
- - corrected_report_indicator@MetaData
  - CORN
  - 2
  - &id002 [nlocs]
  - [-1]
- - ship_call_sign_8_characters@MetaData
  - SHPC8
  - 1
  - *id001
  - [-1, 20]
- - indicator_for_units_of_sea_surface_current_speed@MetaData
  - IUCSPD
  - 2
  - *id002
  - [-1]
- - quips_quality_mark_for_sea_surface_temperature@MetaData
  - QMST
  - 2
  - *id002
  - [-1]
- - year@MetaData
  - YEAR
  - 2
  - *id002
  - [-1]
- - month@MetaData
  - MNTH
  - 2
  - *id002
  - [-1]
- - day@MetaData
  - DAYS
  - 2
  - *id002
  - [-1]
- - hour@MetaData
  - HOUR
  - 3
  - *id002
  - [-1]
- - minute@MetaData
  - MINU
  - 2
  - *id002
  - [-1]
- - second@MetaData
  - SECO
  - 3
  - *id002
  - [-1]
- - receipt_time_significance@MetaData
  - RCTS
  - 2
  - *id002
  - [-1]
- - year_time_of_receipt@MetaData
  - RCYR
  - 2
  - *id002
  - [-1]
- - month_time_of_receipt@MetaData
  - RCMO
  - 2
  - *id002
  - [-1]
- - day_time_of_receipt@MetaData
  - RCDY
  - 2
  - *id002
  - [-1]
- - hour_time_of_receipt@MetaData
  - RCHR
  - 3
  - *id002
  - [-1]
- - minute_time_of_receipt@MetaData
  - RCMI
  - 2
  - *id002
  - [-1]
- - latitude@MetaData
  - CLAT
  - 3
  - *id002
  - [-1]
- - longitude@MetaData
  - CLON
  - 3
  - *id002
  - [-1]
- - height_of_station@MetaData
  - SELV
  - 3
  - *id002
  - [-1]
- - channel_sequence_number@MetaData
  - SEQNUM
  - 1
  - *id001
  - [-1, 20]
- - bulletin_being_monitored_ttaaii@MetaData
  - BUHD
  - 1
  - *id001
  - [-1, 20]
- - bulletin_being_monitored_cccc@MetaData
  - BORG
  - 1
  - *id001
  - [-1, 20]
- - bulletin_being_monitored_yygggg@MetaData
  - BULTIM
  - 1
  - *id001
  - [-1, 20]
- - bulletin_being_monitored_bbb@MetaData
  - BBB
  - 1
  - *id001
  - [-1, 20]
- - averaging_periods_for_trackob_parameters@MetaData
  - AVGPER
  - 2
  - *id002
  - [-1]
- - depth_below_sea_water_surface@ObsValue
  - DBSS
  - 3
  - *id002
  - [-1]
- - sea_temperature_at_specified_depth@ObsValue
  - STMP
  - 3
  - *id002
  - [-1]
- - salinity@ObsValue
  - SALN
  - 3
  - *id002
  - [-1]
- - direction_of_current@ObsValue
  - DROC
  - 3
  - *id002
  - [-1]
- - speed_of_current@ObsValue
  - SPOC
  - 3
  - *id002
  - [-1]
- - buoy_platform_identifier@MetaData
  - BPID
  - 3
  - *id002
  - [-1]
- - stationary_buoy_platform_id@MetaData
  - SBPI
  - 1
  - *id001
  - [-1, 20]
