- - corrected_report_indicator@MetaData
  - CORN
  - 2
  - &id001 [nlocs]
  - [-1]
- - satellite_identifier@MetaData
  - SAID
  - 2
  - *id001
  - [-1]
- - satellite_instruments@MetaData
  - SIID
  - 2
  - *id001
  - [-1]
- - station_acquisition@MetaData
  - STAQ
  - 1
  - &id002 [nlocs, nstring]
  - [-1, 10]
- - software_identification_and_version_number@MetaData
  - SOFTV
  - 1
  - *id002
  - [-1, 10]
- - satellite_cycle_number@MetaData
  - SACYLN
  - 3
  - *id001
  - [-1]
- - orbit_number@MetaData
  - ORBN
  - 3
  - *id001
  - [-1]
- - numerical_model_identifier@MetaData
  - NUMID
  - 1
  - *id002
  - [-1, 10]
- - year@MetaData
  - YEAR
  - 2
  - *id001
  - [-1]
- - month@MetaData
  - MNTH
  - 2
  - *id001
  - [-1]
- - day@MetaData
  - DAYS
  - 2
  - *id001
  - [-1]
- - hour@MetaData
  - HOUR
  - 3
  - *id001
  - [-1]
- - minute@MetaData
  - MINU
  - 2
  - *id001
  - [-1]
- - second_within_a_minute_microsecond_accuracy@MetaData
  - SECW
  - 3
  - *id001
  - [-1]
- - latitude_high_accuracy@MetaData
  - CLATH
  - 3
  - *id001
  - [-1]
- - longitude_high_accuracy@MetaData
  - CLONH
  - 3
  - *id001
  - [-1]
- - remotely_sensed_surface_type@MetaData
  - RSST
  - 2
  - *id001
  - [-1]
- - altimeter_echo_type@MetaData
  - AETP
  - 2
  - *id001
  - [-1]
- - radiometer_sensed_surface_type@MetaData
  - DSST
  - 2
  - *id001
  - [-1]
- - interpolation_flag@MetaData
  - INTF
  - 2
  - *id001
  - [-1]
- - 3d_error_estimate_of_the_navigator_orbit@MetaData
  - EENO
  - 2
  - *id001
  - [-1]
- - altimeter_state_flag@MetaData
  - ASFL
  - 2
  - *id001
  - [-1]
- - altimeter_data_quality_flag@MetaData
  - ADQF
  - 2
  - *id001
  - [-1]
- - altimeter_correction_quality_flag@MetaData
  - ARQF
  - 2
  - *id001
  - [-1]
- - altimeter_rain_flag@MetaData
  - ALRF
  - 2
  - *id001
  - [-1]
- - radiometer_state_flag@MetaData
  - RSFL
  - 2
  - *id001
  - [-1]
- - radiometer_data_quality_flag@MetaData
  - RDQF
  - 2
  - *id001
  - [-1]
- - radiometer_brightness_temperature_interpretation_flag@MetaData
  - RBIF
  - 2
  - *id001
  - [-1]
- - ice_presence_indicator@MetaData
  - IPIN
  - 2
  - *id001
  - [-1]
- - auxilliary_altimeter_state_flags@MetaData
  - AASF
  - 2
  - *id001
  - [-1]
- - meteorological_map_availability@MetaData
  - MMAC
  - 2
  - *id001
  - [-1]
- - interpolation_flag_for_mean_diurnal_tide@MetaData
  - IFDT
  - 2
  - *id001
  - [-1]
- - ku_band_ocean_range@MetaData
  - KBOR
  - 3
  - *id001
  - [-1]
- - rms_of_20_hz_ku_band_ocean_range@MetaData
  - RKBOR
  - 3
  - *id001
  - [-1]
- - number_of_20_hz_valid_points_for_ku_band@MetaData
  - NVPK2
  - 3
  - *id001
  - [-1]
- - ku_band_net_instrumental_correction@MetaData
  - KBIC
  - 3
  - *id001
  - [-1]
- - sea_state_bias_correction_on_ku_band@MetaData
  - SBCK
  - 3
  - *id001
  - [-1]
- - ku_band_significant_wave_height@ObsValue
  - KBSW
  - 3
  - *id001
  - [-1]
- - rms_20_hz_ku_band_significant_wave_height@ObsValue
  - RKSW
  - 3
  - *id001
  - [-1]
- - number_of_20_hz_valid_points_for_ku_band_significant_wa@MetaData
  - NVKSW
  - 3
  - *id001
  - [-1]
- - ku_band_net_instrumental_correction_for_significant_wav@MetaData
  - KNCS
  - 3
  - *id001
  - [-1]
- - ku_band_corrected_ocean_backscatter_coefficient@MetaData
  - KOBC
  - 3
  - *id001
  - [-1]
- - std_ku_band_corrected_ocean_backscatter_coefficient@MetaData
  - SKOBC
  - 3
  - *id001
  - [-1]
- - number_of_valid_points_for_ku_band_backscatter@MetaData
  - NVPKB
  - 3
  - *id001
  - [-1]
- - ku_band_net_instrumental_correction_for_agc@MetaData
  - KNIC
  - 3
  - *id001
  - [-1]
- - attenuation_correction_on_sigma0@MetaData
  - ACRS
  - 3
  - *id001
  - [-1]
- - ku_band_automatic_gain_control@MetaData
  - KAGC
  - 3
  - *id001
  - [-1]
- - rms_ku_band_automatic_gain_control@MetaData
  - RKAGC
  - 3
  - *id001
  - [-1]
- - number_of_valid_points_for_ku_band_automatic_gain_contr@MetaData
  - NVKG
  - 3
  - *id001
  - [-1]
- - c_band_ocean_range@MetaData
  - CBOR
  - 3
  - *id001
  - [-1]
- - rms_of_c_band_ocean_range@MetaData
  - RCBOR
  - 3
  - *id001
  - [-1]
- - number_of_20_hz_valid_points_for_c_band@MetaData
  - NVPC
  - 3
  - *id001
  - [-1]
- - c_band_net_instrumental_correction@MetaData
  - CBIC
  - 3
  - *id001
  - [-1]
- - sea_state_bias_correction_on_c_band@MetaData
  - SBCC
  - 3
  - *id001
  - [-1]
- - c_band_significant_wave_height@ObsValue
  - CBSW
  - 3
  - *id001
  - [-1]
- - rms_20_hz_c_band_significant_wave_height@ObsValue
  - RCSW
  - 3
  - *id001
  - [-1]
- - number_of_20_hz_valid_points_for_c_band_significant_wav@MetaData
  - NVCSW
  - 3
  - *id001
  - [-1]
- - c_band_net_instrumental_correction_for_significant_wave@MetaData
  - CNCS
  - 3
  - *id001
  - [-1]
- - c_band_corrected_ocean_backscatter_coefficient@MetaData
  - CCOB
  - 3
  - *id001
  - [-1]
- - rms_c_band_corrected_ocean_backscatter_coefficient@MetaData
  - RCCOB
  - 3
  - *id001
  - [-1]
- - number_of_valid_points_for_c_band_backscatter@MetaData
  - NVPCB
  - 3
  - *id001
  - [-1]
- - c_band_net_instrumental_correction_for_agc@MetaData
  - CNIA
  - 3
  - *id001
  - [-1]
- - c_band_automatic_gain_control@MetaData
  - CAGC
  - 3
  - *id001
  - [-1]
- - rms_c_band_automatic_gain_control@MetaData
  - RCAGC
  - 3
  - *id001
  - [-1]
- - number_of_valid_points_for_c_band_automatic_gain_contro@MetaData
  - NVPCA
  - 3
  - *id001
  - [-1]
- - satellite_channel_center_frequency@MetaData
  - SCCF
  - 3
  - *id001
  - [-1]
- - brightness_temperature@ObsValue
  - TMBRST
  - 3
  - *id001
  - [-1]
- - radiometer_water_vapor_content@MetaData
  - RWVC
  - 3
  - *id001
  - [-1]
- - radiometer_liquid_content@MetaData
  - RLQC
  - 3
  - *id001
  - [-1]
- - height_or_altitude@MetaData
  - HMSL
  - 3
  - *id001
  - [-1]
- - wind_speed_from_altimeter@ObsValue
  - WSPA
  - 3
  - *id001
  - [-1]
- - wind_speed_from_radiometer@ObsValue
  - WSPR
  - 3
  - *id001
  - [-1]
- - ucomponent_of_the_model_wind_vector@ObsValue
  - UMWV
  - 3
  - *id001
  - [-1]
- - vcomponent_of_the_model_wind_vector@ObsValue
  - VWMV
  - 3
  - *id001
  - [-1]
- - mean_dynamic_topography@MetaData
  - MDYT
  - 3
  - *id001
  - [-1]
- - altitude_of_cog_above_reference_ellipsoid@MetaData
  - ALRE
  - 3
  - *id001
  - [-1]
- - instantaneous_altitude_rate@MetaData
  - IALR
  - 3
  - *id001
  - [-1]
- - squared_off_nadir_angle_of_the_satellite_from_platform@MetaData
  - ONAP
  - 3
  - *id001
  - [-1]
- - squared_off_nadir_angle_of_the_satellite_from_waveform@MetaData
  - SONAW
  - 3
  - *id001
  - [-1]
- - ionospheric_correction_from_model_on_ku_band@MetaData
  - ICMK
  - 3
  - *id001
  - [-1]
- - altimeter_ionospheric_correction_on_ku_band@MetaData
  - AICK
  - 3
  - *id001
  - [-1]
- - model_dry_tropospheric_correction@MetaData
  - MDTC
  - 3
  - *id001
  - [-1]
- - model_wet_tropospheric_correction@MetaData
  - MWTC
  - 3
  - *id001
  - [-1]
- - radiometer_wet_tropospheric_correction@MetaData
  - RWTC
  - 3
  - *id001
  - [-1]
- - mean_seasurface_height@ObsValue
  - MSSH
  - 3
  - *id001
  - [-1]
- - mean_sea_surface_height_from_altimeter_only@ObsValue
  - MSHA
  - 3
  - *id001
  - [-1]
- - geoid's_height@MetaData
  - GEODH
  - 3
  - *id001
  - [-1]
- - ocean_depth/land_elevation@ObsValue
  - ODLE
  - 3
  - *id001
  - [-1]
- - solid_earth_tide_height@MetaData
  - SETH
  - 3
  - *id001
  - [-1]
- - total_geocentric_ocean_tide_height_solution_1@MetaData
  - TGOTH1
  - 3
  - *id001
  - [-1]
- - total_geocentric_ocean_tide_height_solution_2@MetaData
  - TGOTH2
  - 3
  - *id001
  - [-1]
- - loading_tide_height_geocentric_ocean_tide_solution_1@MetaData
  - LTHS1
  - 3
  - *id001
  - [-1]
- - loading_tide_height_geocentric_ocean_tide_solution_2@MetaData
  - LTHS2
  - 3
  - *id001
  - [-1]
- - long_period_tide_height@MetaData
  - LPTH
  - 3
  - *id001
  - [-1]
- - nonequilibrium_long_period_tide_height@MetaData
  - NLTH
  - 3
  - *id001
  - [-1]
- - geocentric_pole_tide_height@MetaData
  - GPTH
  - 3
  - *id001
  - [-1]
- - inverted_barometer_correction@MetaData
  - IBCO
  - 3
  - *id001
  - [-1]
- - high_frequency_fluctuations_of_the_sea_surface_topograp@MetaData
  - HFSTC
  - 3
  - *id001
  - [-1]
- - sea_surface_height_anomoly@ObsValue
  - SSHA
  - 3
  - *id001
  - [-1]
- - channel_sequence_number@MetaData
  - SEQNUM
  - 1
  - *id002
  - [-1, 10]
- - bulletin_being_monitored_ttaaii@MetaData
  - BUHD
  - 1
  - *id002
  - [-1, 10]
- - bulletin_being_monitored_cccc@MetaData
  - BORG
  - 1
  - *id002
  - [-1, 10]
- - bulletin_being_monitored_yygggg@MetaData
  - BULTIM
  - 1
  - *id002
  - [-1, 10]
- - bulletin_being_monitored_bbb@MetaData
  - BBB
  - 1
  - *id002
  - [-1, 10]
- - receipt_time_significance@MetaData
  - RCTS
  - 2
  - *id001
  - [-1]
- - year_time_of_receipt@MetaData
  - RCYR
  - 2
  - *id001
  - [-1]
- - month_time_of_receipt@MetaData
  - RCMO
  - 2
  - *id001
  - [-1]
- - day_time_of_receipt@MetaData
  - RCDY
  - 2
  - *id001
  - [-1]
- - hour_time_of_receipt@MetaData
  - RCHR
  - 3
  - *id001
  - [-1]
- - minute_time_of_receipt@MetaData
  - RCMI
  - 2
  - *id001
  - [-1]
