- - year@MetaData
  - YEAR
  - 2
  - &id001 [nlocs]
  - [-1]
- - month@MetaData
  - MNTH
  - 2
  - *id001
  - [-1]
- - day@MetaData
  - DAYS
  - 2
  - *id001
  - [-1]
- - hour@MetaData
  - HOUR
  - 3
  - *id001
  - [-1]
- - minute@MetaData
  - MINU
  - 2
  - *id001
  - [-1]
- - second@MetaData
  - SECO
  - 3
  - *id001
  - [-1]
- - satellite_identifier@MetaData
  - SAID
  - 2
  - *id001
  - [-1]
- - satellite_cycle_number@MetaData
  - SACYLN
  - 3
  - *id001
  - [-1]
- - satellite_classification@MetaData
  - SCLF
  - 2
  - *id001
  - [-1]
- - orbit_number@MetaData
  - ORBN
  - 3
  - *id001
  - [-1]
- - number_of_observations@MetaData
  - NOBS
  - 3
  - *id001
  - [-1]
- - observation_quality@MetaData
  - OBQL
  - 2
  - *id001
  - [-1]
- - observation_sequence_number@MetaData
  - OSQN
  - 3
  - *id001
  - [-1]
- - latitude_high_accuracy@MetaData
  - CLATH
  - 3
  - *id001
  - [-1]
- - longitude_high_accuracy@MetaData
  - CLONH
  - 3
  - *id001
  - [-1]
- - sealevel_height_deviation_from_8yr_mean_of_19932000@ObsValue
  - SLHD1
  - 3
  - *id001
  - [-1]
- - receipt_time_significance@MetaData
  - RCTS
  - 2
  - *id001
  - [-1]
- - year_time_of_receipt@MetaData
  - RCYR
  - 2
  - *id001
  - [-1]
- - month_time_of_receipt@MetaData
  - RCMO
  - 2
  - *id001
  - [-1]
- - day_time_of_receipt@MetaData
  - RCDY
  - 2
  - *id001
  - [-1]
- - hour_time_of_receipt@MetaData
  - RCHR
  - 3
  - *id001
  - [-1]
- - minute_time_of_receipt@MetaData
  - RCMI
  - 2
  - *id001
  - [-1]
- - raw_report_string@MetaData
  - RRSTG
  - 1
  - [nlocs, nstring]
  - [-1, 10]
