- - corrected_report_indicator@MetaData
  - CORN
  - 2
  - &id001 [nlocs]
  - [-1]
- - satellite_identifier@MetaData
  - SAID
  - 2
  - *id001
  - [-1]
- - year@MetaData
  - YEAR
  - 2
  - *id001
  - [-1]
- - month@MetaData
  - MNTH
  - 2
  - *id001
  - [-1]
- - day@MetaData
  - DAYS
  - 2
  - *id001
  - [-1]
- - hour@MetaData
  - HOUR
  - 3
  - *id001
  - [-1]
- - minute@MetaData
  - MINU
  - 2
  - *id001
  - [-1]
- - second@MetaData
  - SECO
  - 3
  - *id001
  - [-1]
- - latitude_coarse_accuracy@MetaData
  - CLAT
  - 3
  - *id001
  - [-1]
- - longitude_coarse_accuracy@MetaData
  - CLON
  - 3
  - *id001
  - [-1]
- - wind_speed_at_10_meters@ObsValue
  - WS10
  - 3
  - *id001
  - [-1]
- - height_of_waves@ObsValue
  - HOWV
  - 3
  - *id001
  - [-1]
- - standard_deviation_of_significant_wave_height@ObsValue
  - SDWH
  - 3
  - *id001
  - [-1]
- - altitude_platform_to_ellipsoid@MetaData
  - ALTPE
  - 3
  - *id001
  - [-1]
- - peakiness@MetaData
  - PEAK
  - 3
  - *id001
  - [-1]
- - altimeter_correction_ionosphere@MetaData
  - ACIO
  - 3
  - *id001
  - [-1]
- - altimeter_correction_dry_troposphere@MetaData
  - ACDT
  - 3
  - *id001
  - [-1]
- - altimeter_correction_wet_troposphere@MetaData
  - ACWT
  - 3
  - *id001
  - [-1]
- - open_loop_correction_auto_gain_control@MetaData
  - OLCA
  - 3
  - *id001
  - [-1]
- - backscatter@MetaData
  - BKST
  - 3
  - *id001
  - [-1]
- - receipt_time_significance@MetaData
  - RCTS
  - 2
  - *id001
  - [-1]
- - year_time_of_receipt@MetaData
  - RCYR
  - 2
  - *id001
  - [-1]
- - month_time_of_receipt@MetaData
  - RCMO
  - 2
  - *id001
  - [-1]
- - day_time_of_receipt@MetaData
  - RCDY
  - 2
  - *id001
  - [-1]
- - hour_time_of_receipt@MetaData
  - RCHR
  - 3
  - *id001
  - [-1]
- - minute_time_of_receipt@MetaData
  - RCMI
  - 2
  - *id001
  - [-1]
