#!/bin/bash

INPUT_FILES_PATH=/Users/eric2/PROJECTS/GOES16_TEST_FILES/input/00
LATLON_FILE_PATH=/Users/eric2/PROJECTS/GOES16_TEST_FILES/latlon/goes16_lat_lon.nc
OUTPUT_FILE_PATH=/Users/eric2/PROJECTS/GOES16_TEST_FILES/output

python goes16_converter.py $INPUT_FILES_PATH $LATLON_FILE_PATH $OUTPUT_FILE_PATH
