# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.18)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget gnssro_bufr2ioda gnssro_gsidiag2ioda bufr2nc_fortran.x obserror2ioda.x)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target gnssro_bufr2ioda
add_executable(gnssro_bufr2ioda IMPORTED)

# Create imported target gnssro_gsidiag2ioda
add_executable(gnssro_gsidiag2ioda IMPORTED)

# Create imported target bufr2nc_fortran.x
add_executable(bufr2nc_fortran.x IMPORTED)

# Create imported target obserror2ioda.x
add_executable(obserror2ioda.x IMPORTED)

# Import target "gnssro_bufr2ioda" for configuration "RelWithDebInfo"
set_property(TARGET gnssro_bufr2ioda APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(gnssro_bufr2ioda PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/gnssro_bufr2ioda"
  )

# Import target "gnssro_gsidiag2ioda" for configuration "RelWithDebInfo"
set_property(TARGET gnssro_gsidiag2ioda APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(gnssro_gsidiag2ioda PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/gnssro_gsidiag2ioda"
  )

# Import target "bufr2nc_fortran.x" for configuration "RelWithDebInfo"
set_property(TARGET bufr2nc_fortran.x APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(bufr2nc_fortran.x PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/bufr2nc_fortran.x"
  )

# Import target "obserror2ioda.x" for configuration "RelWithDebInfo"
set_property(TARGET obserror2ioda.x APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(obserror2ioda.x PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/obserror2ioda.x"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
