# CMake generated Testfile for 
# Source directory: /home/ubuntu/jedi/ioda-bundle/iodaconv/test
# Build directory: /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_iodaconv_gds2_sst_l2p "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/gds2_sst2ioda.py
                          -i testinput/gds2_sst_l2p.nc
                          -o testrun/gds2_sst_l2p.nc
                          -d 2018041512
                          -t 0.5" "gds2_sst_l2p.nc" "0.0")
set_tests_properties(test_iodaconv_gds2_sst_l2p PROPERTIES  ENVIRONMENT "" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;314;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_gds2_sst_l3u "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/gds2_sst2ioda.py
                          -i testinput/gds2_sst_l3u.nc
                          -o testrun/gds2_sst_l3u.nc
                          -d 2018041512
                          -t 0.5" "gds2_sst_l3u.nc" "0.0")
set_tests_properties(test_iodaconv_gds2_sst_l3u PROPERTIES  ENVIRONMENT "" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;327;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_smap_sss "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/smap_sss2ioda.py
                          -i testinput/smap_sss_rss.nc
                          -o testrun/smap_sss_rss.nc
                          -d 2018041512" "smap_sss_rss.nc" "0.0")
set_tests_properties(test_iodaconv_smap_sss PROPERTIES  ENVIRONMENT "" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;340;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_rads_adt "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/rads_adt2ioda.py
                          -i testinput/rads_adt.nc
                          -o testrun/rads_adt.nc
                          -d 2018041512" "rads_adt.nc" "0.0")
set_tests_properties(test_iodaconv_rads_adt PROPERTIES  ENVIRONMENT "" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;352;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_godae_prof "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/godae_profile2ioda.py
                          -i testinput/godae_prof.bin
                          -o testrun/godae_prof.nc
                          -d 1998092212" "godae_prof.nc" "0.0")
set_tests_properties(test_iodaconv_godae_prof PROPERTIES  ENVIRONMENT "" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;364;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_godae_ship "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/godae_ship2ioda.py
                          -i testinput/godae_ship.bin
                          -o testrun/godae_ship.nc
                          -d 1998090112" "godae_ship.nc" "0.0")
set_tests_properties(test_iodaconv_godae_ship PROPERTIES  ENVIRONMENT "" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;376;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_godae_trak "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/godae_trak2ioda.py
                          -i testinput/godae_trak.bin
                          -o testrun/godae_trak.nc
                          -d 2004070812" "godae_trak.nc" "0.0")
set_tests_properties(test_iodaconv_godae_trak PROPERTIES  ENVIRONMENT "" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;388;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_hgodas_adt "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/hgodas_adt2ioda.py
                          -i testinput/hgodas_adt.nc
                          -o testrun/hgodas_adt.nc
                          -d 2018041512" "hgodas_adt.nc" "0.0")
set_tests_properties(test_iodaconv_hgodas_adt PROPERTIES  ENVIRONMENT "" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;400;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_hgodas_insitu "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/hgodas_insitu2ioda.py
                          -i testinput/hgodas_insitu.nc
                          -o testrun/hgodas_insitu.nc
                          -d 2018041512" "hgodas_insitu.nc" "0.0")
set_tests_properties(test_iodaconv_hgodas_insitu PROPERTIES  ENVIRONMENT "" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;412;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_hgodas_sst "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/hgodas_sst2ioda.py
                          -i testinput/hgodas_sst.nc
                          -o testrun/hgodas_sst.nc
                          -d 2018041512" "hgodas_sst.nc" "0.0")
set_tests_properties(test_iodaconv_hgodas_sst PROPERTIES  ENVIRONMENT "" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;424;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_glider "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/glider2ioda.py
                          -i testinput/marineglider_AOML.nc
                          -o testrun/test_glider.nc
                          -d 2016080412
                          -y testinput/glider.yaml" "test_glider.nc" "0.0")
set_tests_properties(test_iodaconv_glider PROPERTIES  ENVIRONMENT "" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;436;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_hfradar "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/ndbc_hfradar2ioda.py
                          -i testinput/ndbc_hfradar_in.nc
                          -o testrun/ndbc_hfradar_out.nc
                          -d 2020072012" "ndbc_hfradar_out.nc" "0.0")
set_tests_properties(test_iodaconv_hfradar PROPERTIES  ENVIRONMENT "" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;449;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_argoclim "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/argoClim2ioda.py
                          -i testinput/argoclim_test.nc
                          -o testrun/argoclim.nc
                          -d 2004010200" "argoclim.nc" "0.0")
set_tests_properties(test_iodaconv_argoclim PROPERTIES  ENVIRONMENT "" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;461;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_cryosat2 "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/cryosat_ice2ioda.py
                          -i testinput/cryosat2_L2_test.nc
                          -o testrun/cryosat2_L2.nc
                          -d 2019092112" "cryosat2_L2.nc" "0.0")
set_tests_properties(test_iodaconv_cryosat2 PROPERTIES  ENVIRONMENT "" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;473;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_emc_ice "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/emc_ice2ioda.py
                          -i testinput/emc_ice.nc
                          -o testrun/emc_ice_ioda2.nc
                          -d 2015082812" "emc_ice_ioda2.nc" "0.0")
set_tests_properties(test_iodaconv_emc_ice PROPERTIES  ENVIRONMENT "" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;485;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_smos_sss "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/smos_sss2ioda.py
                          -i testinput/SM_REPR_MIR_OSUDP2_20100601T000131_20100601T001849_662_120_1.nc
                          -o testrun/smos_sss_l2.nc
                          -d 2010060100" "smos_sss_l2.nc" "0.0")
set_tests_properties(test_iodaconv_smos_sss PROPERTIES  ENVIRONMENT "" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;497;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_copernicus_l4adt "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/copernicus_l4adt2ioda.py
                          -i testinput/dt_global_twosat_phy_l4_20150101_vDT2018.nc
                          -o testrun/ioda_dt_global_twosat_phy_l4_20150101_vDT2018.nc" "ioda_dt_global_twosat_phy_l4_20150101_vDT2018.nc" "0.0")
set_tests_properties(test_iodaconv_copernicus_l4adt PROPERTIES  ENVIRONMENT "" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;509;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_copernicus_l3swh "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/copernicus_l3swh2ioda.py
                          -i testinput/global_vavh_l3_rt_s3a_20210930T18.nc
                          -o testrun/ioda_global_vavh_l3_rt_s3a_20210930T18.nc" "ioda_global_vavh_l3_rt_s3a_20210930T18.nc" "0.0")
set_tests_properties(test_iodaconv_copernicus_l3swh PROPERTIES  ENVIRONMENT "" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;520;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_avhrr_radiance "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/avhrr_radiance2ioda.py    
                          -i testinput/avhrr_radiance.nc
                          -o testrun/avhrr_radiance.nc                               
                          -d 2015010100" "avhrr_radiance.nc" "0.0")
set_tests_properties(test_iodaconv_avhrr_radiance PROPERTIES  ENVIRONMENT "" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;531;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_satwinds "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/amv_ssec_ascii2ioda.py
                          -i testinput/satwinds_ssec2021080103.txt
                          -o testrun/satwinds_ssec2021080103.nc
                          -d 2021080103" "satwinds_ssec2021080103.nc" "0.0")
set_tests_properties(test_iodaconv_satwinds PROPERTIES  ENVIRONMENT "" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;547;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_metar "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/metar_csv2ioda.py
                          -i testinput/2020100106_metars_small.csv
                          -o testrun/2020100106_metars_small.nc
                          -d 2020100106" "2020100106_metars_small.nc" "0.0")
set_tests_properties(test_iodaconv_metar PROPERTIES  ENVIRONMENT "" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;563;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_viirs_jpss1_oc_l2 "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/viirs_modis_l2_oc2ioda.py
                          -i testinput/viirs_jpss1_oc_l2.nc
                          -o testrun/viirs_jpss1_oc_l2.nc
                          -d 2018041512
                          -t 0.5" "viirs_jpss1_oc_l2.nc" "0.0")
set_tests_properties(test_iodaconv_viirs_jpss1_oc_l2 PROPERTIES  ENVIRONMENT "" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;579;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_modis_aqua_oc_l2 "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/viirs_modis_l2_oc2ioda.py
                          -i testinput/modis_aqua_oc_l2.nc
                          -o testrun/modis_aqua_oc_l2.nc
                          -d 2018041512
                          -t 0.5" "modis_aqua_oc_l2.nc" "0.0")
set_tests_properties(test_iodaconv_modis_aqua_oc_l2 PROPERTIES  ENVIRONMENT "" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;592;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_viirs_jpss1_oc_l3 "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/viirs_modis_l3_oc2ioda.py
                          -i testinput/viirs_jpss1_oc_l3.nc
                          -o testrun/viirs_jpss1_oc_l3.nc
                          -d 2018041512" "viirs_jpss1_oc_l3.nc" "0.0")
set_tests_properties(test_iodaconv_viirs_jpss1_oc_l3 PROPERTIES  ENVIRONMENT "" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;605;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_godae_bgc_argo "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/godae_bgc_argo2ioda.py
                          -i testinput/godae_bgc_argo.nc
                          -o testrun/godae_bgc_argo.nc
                          -d 2018041512" "godae_bgc_argo.nc" "0.0")
set_tests_properties(test_iodaconv_godae_bgc_argo PROPERTIES  ENVIRONMENT "" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;617;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_ncep_bufr "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/ncep_classes.py
                          -p testinput/
                          -i b001xx007.20200310.bufr
                          -o testrun/ioda.NC001007.2020031012.nc
                          -d 2020031012
                          -m 5
                          -l NC001007.yaml
                          -ot NC001007" "ioda.NC001007.2020031012.nc" "0.0")
set_tests_properties(test_iodaconv_ncep_bufr PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;629;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_gen_singleob "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/gen_single_ob.py
                          -y testinput/singleob.yaml" "singleob.nc" "0.0")
set_tests_properties(test_iodaconv_gen_singleob PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;644;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_giirs_ssec2ioda "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/giirs_ssec2ioda.py
                          -i testinput/giirs_fy4a-test.nc
                          -o testrun/giirs_ssec_ioda.nc4
                          -d 2017030208" "giirs_ssec_ioda.nc4" "0.5e-4")
set_tests_properties(test_iodaconv_giirs_ssec2ioda PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;658;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_giirs_lw "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/giirs_lw2ioda.py
                          -i testinput/giirs_fy4a-test.nc
                          -o testrun/giirs_fy4a_obs_2017030208.nc4
                          -d 2017030208" "giirs_fy4a_obs_2017030208.nc4" "0.0")
set_tests_properties(test_iodaconv_giirs_lw PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;669;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_gsidiag_conv_uv "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/test_gsidiag.py
                          -i testinput/gsidiag_conv_uv_testinput.nc
                          -o testrun/
                          -t conv
                          -p satwind" "satwind_obs_2018041500.nc4" "0.0")
set_tests_properties(test_iodaconv_gsidiag_conv_uv PROPERTIES  ENVIRONMENT "" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;684;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_gsidiag_conv "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/test_gsidiag.py
                          -i testinput/gsidiag_conv_t_sfc_test.nc
                          -o testrun/
                          -t conv
                          -p sfc" "sfc_tv_obs_2018041500.nc4" "0.0")
set_tests_properties(test_iodaconv_gsidiag_conv PROPERTIES  ENVIRONMENT "" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;697;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_gsidiag_rad "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/test_gsidiag.py
                          -i testinput/gsidiag_amsua_aqua_radiance_test.nc
                          -o testrun/
                          -t rad" "amsua_aqua_obs_2018041500.nc4" "0.0")
set_tests_properties(test_iodaconv_gsidiag_rad PROPERTIES  ENVIRONMENT "" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;710;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_wrfdadiag_rad "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/test_wrfdadiag.py
                          -i testinput/wrfdadiags_goes-16-abi_2018041500.nc
                          -o testrun/
                          -t rad" "abi_g16_obs_2018041500.nc4" "0.0")
set_tests_properties(test_iodaconv_wrfdadiag_rad PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;726;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_gnssro_bufr_conv "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/gnssro_bufr2ioda
                            2018041500
                            testinput/gnssro_kompsat5_20180415_00Z.bufr
                            testrun/gnssro_kompsat5_2018041500.nc4" "gnssro_kompsat5_2018041500.nc4" "0.0")
set_tests_properties(test_iodaconv_gnssro_bufr_conv PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;742;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_viirs_aod "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/viirs_aod2ioda.py
                          -i testinput/viirs_aod.nc 
                          -o testrun/viirs_aod.nc
                          -m nesdis
                          -k maskout
                          -n 0.0" "viirs_aod.nc" "0.0")
set_tests_properties(test_iodaconv_viirs_aod PROPERTIES  ENVIRONMENT "" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;759;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_satbias_viirs_aod "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/viirs_biaswriter.py
                          -o testrun/viirs_bias.nc" "viirs_bias.nc" "0.0")
set_tests_properties(test_iodaconv_satbias_viirs_aod PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;773;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_tropomi_no2 "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/tropomi_no2_nc2ioda.py
                          -i testinput/tropomi_no2.nc
                          -o testrun/tropomi_no2.nc" "tropomi_no2.nc" "0.0")
set_tests_properties(test_iodaconv_tropomi_no2 PROPERTIES  ENVIRONMENT "" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;782;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_mopitt_co "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/mopitt_co_nc2ioda.py
                          -i testinput/mopitt_co.he5
                          -o testrun/mopitt_co.nc" "mopitt_co.nc" "0.0")
set_tests_properties(test_iodaconv_mopitt_co PROPERTIES  ENVIRONMENT "" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;793;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_modis_aod "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/modis_aod2ioda.py
                          -i testinput/modis_aod.nc
                          -t 2016060100
                          -o testrun/modis_aod.nc" "modis_aod.nc" "0.0")
set_tests_properties(test_iodaconv_modis_aod PROPERTIES  ENVIRONMENT "" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;804;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_aeronet_aod "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/aeronet_aod2ioda.py
                          -i testinput/aeronet_aod.dat
                          -o testrun/aeronet_aod.nc" "aeronet_aod.nc" "0.0")
set_tests_properties(test_iodaconv_aeronet_aod PROPERTIES  ENVIRONMENT "" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;816;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_aeronet_aaod "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/aeronet_aaod2ioda.py
			  -c testinput/aeronet_cad.dat
			  -t testinput/aeronet_tab.dat
			  -o testrun/aeronet_aaod.nc" "aeronet_aaod.nc" "0.0")
set_tests_properties(test_iodaconv_aeronet_aaod PROPERTIES  ENVIRONMENT "" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;827;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_airnow "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/airnow2ioda-nc.py
                          -i testinput/airnow_2020081306.dat
                          -s testinput/airnow_sites.dat
                          -o testrun/airnow_2020081306.nc" "airnow_2020081306.nc" "0.0")
set_tests_properties(test_iodaconv_airnow PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;839;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_atms_nc4 "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/src/hdf5/atms_netcdf_hdf5_2ioda.py
                          -d 2021120600
                          -i testinput/SNDR_SNPP_ATMS_SAMPLE.nc4
                          -o testrun/2021120600_atms_sdr.nc4" "2021120600_atms_sdr.nc4" "0.0")
set_tests_properties(test_iodaconv_atms_nc4 PROPERTIES  ENVIRONMENT "" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1086;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_gnssro_conv "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/bufr2nc_fortran.x
                            -i testinput -o testrun gnssro_kompsat5_20180415_00Z.bufr" "gnssro_obs_2018041500.nc4" "0.0")
set_tests_properties(test_iodaconv_gnssro_conv PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1185;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_prepbufr_conv "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/bufr2nc_fortran.x
                            -i testinput -o testrun prepbufr.bufr" "sondes_obs_2020093018.nc4" "0.5e-4")
set_tests_properties(test_iodaconv_prepbufr_conv PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1195;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_mhs_conv "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/bufr2nc_fortran.x
                            -i testinput -o testrun gdas.t18z.1bmhs.tm00.bufr_d" "mhs_metop-b_obs_2020101215.nc4" "0.0")
set_tests_properties(test_iodaconv_mhs_conv PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1205;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_obserror "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/obserror2ioda.x testinput/Rcov_iasi_metop-b_sea.bin testrun/Rcov_iasi_metop-b_sea.nc4" "Rcov_iasi_metop-b_sea.nc4" "0.0")
set_tests_properties(test_iodaconv_obserror PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1259;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_ghcn_snod "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/ghcn_snod2ioda.py
                          -i testinput/ghcn_20200228.csv
                          -o testrun/ghcn_snod_20200228.nc
                          -f /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/doc/fix/ghcn-stations.txt
                          -d 20200228
                          -m maskout" "ghcn_snod_20200228.nc" "0.0")
set_tests_properties(test_iodaconv_ghcn_snod PROPERTIES  ENVIRONMENT "" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1300;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_smap_ssm "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/smap_ssm2ioda.py
                            -i testinput/SMAP_L2_SM_P_NRT_24342_A_20190822T224858_N16023_002.h5
                            -o testrun/smap_ssm.nc
                            -m maskout" "smap_ssm.nc" "0.0")
set_tests_properties(test_iodaconv_smap_ssm PROPERTIES  ENVIRONMENT "" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1314;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_smos_ssm "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/smos_ssm2ioda.py
                            -i testinput/smos_l2nrt_ssm.nc
                            -o testrun/smos_ssm.nc
                            -m maskout" "smos_ssm.nc" "0.0")
set_tests_properties(test_iodaconv_smos_ssm PROPERTIES  ENVIRONMENT "" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1326;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_ascat_ssm "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/ascat_ssm2ioda.py
                            -i testinput/ascat_ssm.nc
                            -o testrun/ascat_ssm.nc
                            -m maskout" "ascat_ssm.nc" "0.0")
set_tests_properties(test_iodaconv_ascat_ssm PROPERTIES  ENVIRONMENT "" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1338;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_imsfv3_scf "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/imsfv3_scf2ioda.py
                            -i testinput/imsscf_20191215_c48.nc
                            -o testrun/imsfv3_scf.nc" "imsfv3_scf.nc" "0.0")
set_tests_properties(test_iodaconv_imsfv3_scf PROPERTIES  ENVIRONMENT "" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1350;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_smap9km_ssm "bash" "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/smap9km_ssm2ioda.py
                            -i testinput/SMAP_L2_SM_P_E_36365_D_20211122T013945_R18240_001.h5
                            -o testrun/smap9km_ssm.nc
                            -m maskout" "smap9km_ssm.nc" "0.0")
set_tests_properties(test_iodaconv_smap9km_ssm PROPERTIES  ENVIRONMENT "" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1361;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(test_iodaconv_land_owp_snow_obs_dup_thin "/home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/iodaconv_comp.sh" "netcdf" "/usr/bin/python3.8 /home/ubuntu/jedi/ioda-bundle/iodaconv/bld/bin/owp_snow_obs.py
                          -i testinput/owp_snow_obs.csv
                          -o testrun/owp_snow_obs_dup_thin_err_fn.nc
			  --thin_swe 1 --thin_depth .5 --thin_random_seed 3  --err_fn dummy_err" "owp_snow_obs_dup_thin_err_fn.nc" "0.0")
set_tests_properties(test_iodaconv_land_owp_snow_obs_dup_thin PROPERTIES  ENVIRONMENT "" LABELS "iodaconv;script" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1373;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_2020100106_metars_small.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/2020100106_metars_small.nc")
set_tests_properties(iodaconv_validate_testoutput_2020100106_metars_small.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_2021120600_atms_sdr.nc4 "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/2021120600_atms_sdr.nc4")
set_tests_properties(iodaconv_validate_testoutput_2021120600_atms_sdr.nc4 PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_NC005031.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/NC005031.nc")
set_tests_properties(iodaconv_validate_testoutput_NC005031.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_NC005066.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/NC005066.nc")
set_tests_properties(iodaconv_validate_testoutput_NC005066.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_Rcov_iasi_metop-b_sea.nc4 "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/Rcov_iasi_metop-b_sea.nc4")
set_tests_properties(iodaconv_validate_testoutput_Rcov_iasi_metop-b_sea.nc4 PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_abi_g16_obs_2018041500.nc4 "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/abi_g16_obs_2018041500.nc4")
set_tests_properties(iodaconv_validate_testoutput_abi_g16_obs_2018041500.nc4 PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_aeronet_aaod.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/aeronet_aaod.nc")
set_tests_properties(iodaconv_validate_testoutput_aeronet_aaod.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_aeronet_aod.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/aeronet_aod.nc")
set_tests_properties(iodaconv_validate_testoutput_aeronet_aod.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_afwa_snod.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/afwa_snod.nc")
set_tests_properties(iodaconv_validate_testoutput_afwa_snod.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_airep_multi.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/airep_multi.nc")
set_tests_properties(iodaconv_validate_testoutput_airep_multi.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_airnow_2020081306.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/airnow_2020081306.nc")
set_tests_properties(iodaconv_validate_testoutput_airnow_2020081306.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_amdar_single.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/amdar_single.nc")
set_tests_properties(iodaconv_validate_testoutput_amdar_single.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_amdar_wmo_multi.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/amdar_wmo_multi.nc")
set_tests_properties(iodaconv_validate_testoutput_amdar_wmo_multi.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_amdar_wmo_multi2.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/amdar_wmo_multi2.nc")
set_tests_properties(iodaconv_validate_testoutput_amdar_wmo_multi2.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_amsua_aqua_obs_2018041500.nc4 "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/amsua_aqua_obs_2018041500.nc4")
set_tests_properties(iodaconv_validate_testoutput_amsua_aqua_obs_2018041500.nc4 PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_aod_viirs_obs_2018041500_s.nc4 "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/aod_viirs_obs_2018041500_s.nc4")
set_tests_properties(iodaconv_validate_testoutput_aod_viirs_obs_2018041500_s.nc4 PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_argoclim.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/argoclim.nc")
set_tests_properties(iodaconv_validate_testoutput_argoclim.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_ascat_ssm.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/ascat_ssm.nc")
set_tests_properties(iodaconv_validate_testoutput_ascat_ssm.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_avhrr_radiance.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/avhrr_radiance.nc")
set_tests_properties(iodaconv_validate_testoutput_avhrr_radiance.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_bufr_read_2_dim_blocks.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/bufr_read_2_dim_blocks.nc")
set_tests_properties(iodaconv_validate_testoutput_bufr_read_2_dim_blocks.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_bufr_read_wmo_radiosonde.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/bufr_read_wmo_radiosonde.nc")
set_tests_properties(iodaconv_validate_testoutput_bufr_read_wmo_radiosonde.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_buoy_single.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/buoy_single.nc")
set_tests_properties(iodaconv_validate_testoutput_buoy_single.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_buoy_wmo_multi.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/buoy_wmo_multi.nc")
set_tests_properties(iodaconv_validate_testoutput_buoy_wmo_multi.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_buoy_wmo_multi2.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/buoy_wmo_multi2.nc")
set_tests_properties(iodaconv_validate_testoutput_buoy_wmo_multi2.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_cryosat2_L2.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/cryosat2_L2.nc")
set_tests_properties(iodaconv_validate_testoutput_cryosat2_L2.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_emc_ice_ioda2.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/emc_ice_ioda2.nc")
set_tests_properties(iodaconv_validate_testoutput_emc_ice_ioda2.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_gdas.aircar.t00z.20210801.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/gdas.aircar.t00z.20210801.nc")
set_tests_properties(iodaconv_validate_testoutput_gdas.aircar.t00z.20210801.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_gdas.t00z.1bhrs4.tm00.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/gdas.t00z.1bhrs4.tm00.nc")
set_tests_properties(iodaconv_validate_testoutput_gdas.t00z.1bhrs4.tm00.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_gdas.t06z.adpsfc.tm00.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/gdas.t06z.adpsfc.tm00.nc")
set_tests_properties(iodaconv_validate_testoutput_gdas.t06z.adpsfc.tm00.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_gdas.t06z.adpsfc_snow.tm00.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/gdas.t06z.adpsfc_snow.tm00.nc")
set_tests_properties(iodaconv_validate_testoutput_gdas.t06z.adpsfc_snow.tm00.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_gdas.t18z.1bmhs.tm00.15.7.filter_split.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/gdas.t18z.1bmhs.tm00.15.7.filter_split.nc")
set_tests_properties(iodaconv_validate_testoutput_gdas.t18z.1bmhs.tm00.15.7.filter_split.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_gdas.t18z.1bmhs.tm00.15.seven.split.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/gdas.t18z.1bmhs.tm00.15.seven.split.nc")
set_tests_properties(iodaconv_validate_testoutput_gdas.t18z.1bmhs.tm00.15.seven.split.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_gdas.t18z.1bmhs.tm00.filtering.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/gdas.t18z.1bmhs.tm00.filtering.nc")
set_tests_properties(iodaconv_validate_testoutput_gdas.t18z.1bmhs.tm00.filtering.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_gdas.t18z.1bmhs.tm00.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/gdas.t18z.1bmhs.tm00.nc")
set_tests_properties(iodaconv_validate_testoutput_gdas.t18z.1bmhs.tm00.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_gds2_sst_l2p.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/gds2_sst_l2p.nc")
set_tests_properties(iodaconv_validate_testoutput_gds2_sst_l2p.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_gds2_sst_l3u.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/gds2_sst_l3u.nc")
set_tests_properties(iodaconv_validate_testoutput_gds2_sst_l3u.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_ghcn_snod_20200228.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/ghcn_snod_20200228.nc")
set_tests_properties(iodaconv_validate_testoutput_ghcn_snod_20200228.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_giirs_fy4a_obs_2017030208.nc4 "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/giirs_fy4a_obs_2017030208.nc4")
set_tests_properties(iodaconv_validate_testoutput_giirs_fy4a_obs_2017030208.nc4 PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_giirs_ssec_ioda.nc4 "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/giirs_ssec_ioda.nc4")
set_tests_properties(iodaconv_validate_testoutput_giirs_ssec_ioda.nc4 PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_gnssro_2020-306-2358C2E6.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/gnssro_2020-306-2358C2E6.nc")
set_tests_properties(iodaconv_validate_testoutput_gnssro_2020-306-2358C2E6.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_gnssro_cosmic2_2021080212.nc4 "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/gnssro_cosmic2_2021080212.nc4")
set_tests_properties(iodaconv_validate_testoutput_gnssro_cosmic2_2021080212.nc4 PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_gnssro_kompsat5_2018041500.nc4 "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/gnssro_kompsat5_2018041500.nc4")
set_tests_properties(iodaconv_validate_testoutput_gnssro_kompsat5_2018041500.nc4 PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_gnssro_obs_2018041500.nc4 "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/gnssro_obs_2018041500.nc4")
set_tests_properties(iodaconv_validate_testoutput_gnssro_obs_2018041500.nc4 PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_godae_bgc_argo.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/godae_bgc_argo.nc")
set_tests_properties(iodaconv_validate_testoutput_godae_bgc_argo.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_godae_prof.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/godae_prof.nc")
set_tests_properties(iodaconv_validate_testoutput_godae_prof.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_godae_ship.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/godae_ship.nc")
set_tests_properties(iodaconv_validate_testoutput_godae_ship.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_godae_trak.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/godae_trak.nc")
set_tests_properties(iodaconv_validate_testoutput_godae_trak.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_hgodas_adt.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/hgodas_adt.nc")
set_tests_properties(iodaconv_validate_testoutput_hgodas_adt.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_hgodas_insitu.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/hgodas_insitu.nc")
set_tests_properties(iodaconv_validate_testoutput_hgodas_insitu.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_hgodas_sst.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/hgodas_sst.nc")
set_tests_properties(iodaconv_validate_testoutput_hgodas_sst.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_imsfv3_scf.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/imsfv3_scf.nc")
set_tests_properties(iodaconv_validate_testoutput_imsfv3_scf.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_imssnow_scf.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/imssnow_scf.nc")
set_tests_properties(iodaconv_validate_testoutput_imssnow_scf.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_ioda.NC001007.2020031012.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/ioda.NC001007.2020031012.nc")
set_tests_properties(iodaconv_validate_testoutput_ioda.NC001007.2020031012.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_ioda_dt_global_twosat_phy_l4_20150101_vDT2018.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/ioda_dt_global_twosat_phy_l4_20150101_vDT2018.nc")
set_tests_properties(iodaconv_validate_testoutput_ioda_dt_global_twosat_phy_l4_20150101_vDT2018.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_ioda_global_vavh_l3_rt_s3a_20210930T18.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/ioda_global_vavh_l3_rt_s3a_20210930T18.nc")
set_tests_properties(iodaconv_validate_testoutput_ioda_global_vavh_l3_rt_s3a_20210930T18.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_mhs_metop-b_obs_2020101215.nc4 "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/mhs_metop-b_obs_2020101215.nc4")
set_tests_properties(iodaconv_validate_testoutput_mhs_metop-b_obs_2020101215.nc4 PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_modis_aod.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/modis_aod.nc")
set_tests_properties(iodaconv_validate_testoutput_modis_aod.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_modis_aqua_oc_l2.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/modis_aqua_oc_l2.nc")
set_tests_properties(iodaconv_validate_testoutput_modis_aqua_oc_l2.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_mopitt_co.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/mopitt_co.nc")
set_tests_properties(iodaconv_validate_testoutput_mopitt_co.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_ndbc_hfradar_out.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/ndbc_hfradar_out.nc")
set_tests_properties(iodaconv_validate_testoutput_ndbc_hfradar_out.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_odb_sonde_16019.nc4 "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/odb_sonde_16019.nc4")
set_tests_properties(iodaconv_validate_testoutput_odb_sonde_16019.nc4 PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_owp_snow_obs_dup_thin_err_fn.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/owp_snow_obs_dup_thin_err_fn.nc")
set_tests_properties(iodaconv_validate_testoutput_owp_snow_obs_dup_thin_err_fn.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_rads_adt.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/rads_adt.nc")
set_tests_properties(iodaconv_validate_testoutput_rads_adt.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_rass_wmo_multi.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/rass_wmo_multi.nc")
set_tests_properties(iodaconv_validate_testoutput_rass_wmo_multi.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_satbias_amsua_n18.nc4 "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/satbias_amsua_n18.nc4")
set_tests_properties(iodaconv_validate_testoutput_satbias_amsua_n18.nc4 PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_satbias_cris_npp.nc4 "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/satbias_cris_npp.nc4")
set_tests_properties(iodaconv_validate_testoutput_satbias_cris_npp.nc4 PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_satbias_ssmis_f16.nc4 "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/satbias_ssmis_f16.nc4")
set_tests_properties(iodaconv_validate_testoutput_satbias_ssmis_f16.nc4 PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_satwind_EUMet.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/satwind_EUMet.nc")
set_tests_properties(iodaconv_validate_testoutput_satwind_EUMet.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_satwind_Himawari.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/satwind_Himawari.nc")
set_tests_properties(iodaconv_validate_testoutput_satwind_Himawari.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_satwind_Insat.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/satwind_Insat.nc")
set_tests_properties(iodaconv_validate_testoutput_satwind_Insat.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_satwind_obs_2018041500.nc4 "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/satwind_obs_2018041500.nc4")
set_tests_properties(iodaconv_validate_testoutput_satwind_obs_2018041500.nc4 PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_satwinds_ssec2021080103.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/satwinds_ssec2021080103.nc")
set_tests_properties(iodaconv_validate_testoutput_satwinds_ssec2021080103.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_sfc_tv_obs_2018041500.nc4 "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/sfc_tv_obs_2018041500.nc4")
set_tests_properties(iodaconv_validate_testoutput_sfc_tv_obs_2018041500.nc4 PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_ship_single.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/ship_single.nc")
set_tests_properties(iodaconv_validate_testoutput_ship_single.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_ship_wmo_multi.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/ship_wmo_multi.nc")
set_tests_properties(iodaconv_validate_testoutput_ship_wmo_multi.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_ship_wmo_multi2.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/ship_wmo_multi2.nc")
set_tests_properties(iodaconv_validate_testoutput_ship_wmo_multi2.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_singleob.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/singleob.nc")
set_tests_properties(iodaconv_validate_testoutput_singleob.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_smap9km_ssm.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/smap9km_ssm.nc")
set_tests_properties(iodaconv_validate_testoutput_smap9km_ssm.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_smap_ssm.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/smap_ssm.nc")
set_tests_properties(iodaconv_validate_testoutput_smap_ssm.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_smap_sss_rss.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/smap_sss_rss.nc")
set_tests_properties(iodaconv_validate_testoutput_smap_sss_rss.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_smos_ssm.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/smos_ssm.nc")
set_tests_properties(iodaconv_validate_testoutput_smos_ssm.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_smos_sss_l2.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/smos_sss_l2.nc")
set_tests_properties(iodaconv_validate_testoutput_smos_sss_l2.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_sondes_obs_2020093018.nc4 "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/sondes_obs_2020093018.nc4")
set_tests_properties(iodaconv_validate_testoutput_sondes_obs_2020093018.nc4 PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_synop_single.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/synop_single.nc")
set_tests_properties(iodaconv_validate_testoutput_synop_single.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_synop_wmo_multi.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/synop_wmo_multi.nc")
set_tests_properties(iodaconv_validate_testoutput_synop_wmo_multi.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_synop_wmo_multi2.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/synop_wmo_multi2.nc")
set_tests_properties(iodaconv_validate_testoutput_synop_wmo_multi2.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_test_glider.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/test_glider.nc")
set_tests_properties(iodaconv_validate_testoutput_test_glider.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_tropomi_no2.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/tropomi_no2.nc")
set_tests_properties(iodaconv_validate_testoutput_tropomi_no2.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_vadwinds_wmo_multi.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/vadwinds_wmo_multi.nc")
set_tests_properties(iodaconv_validate_testoutput_vadwinds_wmo_multi.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_viirs_aod.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/viirs_aod.nc")
set_tests_properties(iodaconv_validate_testoutput_viirs_aod.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_viirs_bias.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/viirs_bias.nc")
set_tests_properties(iodaconv_validate_testoutput_viirs_bias.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_viirs_jpss1_oc_l2.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/viirs_jpss1_oc_l2.nc")
set_tests_properties(iodaconv_validate_testoutput_viirs_jpss1_oc_l2.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_viirs_jpss1_oc_l3.nc "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/viirs_jpss1_oc_l3.nc")
set_tests_properties(iodaconv_validate_testoutput_viirs_jpss1_oc_l3.nc PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_wmo_raob_double.nc4 "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/wmo_raob_double.nc4")
set_tests_properties(iodaconv_validate_testoutput_wmo_raob_double.nc4 PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
add_test(iodaconv_validate_testoutput_wmo_raob_quadruple.nc4 "ioda-validate.x" "/validation/ObsSpace.yaml" "/home/ubuntu/jedi/ioda-bundle/iodaconv/test/testoutput/wmo_raob_quadruple.nc4")
set_tests_properties(iodaconv_validate_testoutput_wmo_raob_quadruple.nc4 PROPERTIES  ENVIRONMENT "ECKIT_COLOUR_OUTPUT=1;OMP_NUM_THREADS=1" LABELS "iodaconv;script;iodaconv_validate" _BACKTRACE_TRIPLES "/usr/local/share/ecbuild/cmake/ecbuild_add_test.cmake;438;add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;1396;ecbuild_add_test;/home/ubuntu/jedi/ioda-bundle/iodaconv/test/CMakeLists.txt;0;")
