@startuml
hide footbox
skinparam dpi 300
skinparam SequenceActorBorderThickness 2
skinparam SequenceActorBorderColor #firebrick
skinparam ActorBackgroundColor #lightyellow
skinparam ParticipantBackgroundColor #lightyellow
skinparam ParticipantBorderThickness 2
skinparam ParticipantBorderColor #firebrick

autonumber

actor User
participant QuerySet
participant QueryParser
participant Tokenizer

create QuerySet
User -> QuerySet : QuerySet()
User -> QuerySet : add("longitude", "*/CLON")
QuerySet -> QueryParser : parse(queryString)
activate QueryParser
    QueryParser -> Tokenizer : tokenize(queryString)
    Tokenizer --> QueryParser : tokens

    loop all sub-queries
        create Query
        QueryParser -> Query : Query()

        loop all components
            create QueryComponent
            QueryParser -> QueryComponent : QueryComponent()
            QueryParser -> Query : push_back(component)
        end
    end

    QueryParser --> QuerySet : queries
deactivate QueryParser
@enduml